"""Argmax over a packed bus of K signed elements.

Combinational tournament tree. Output is a ``ceil(log2(K))``-bit unsigned
index.  K = 49152 (SmolLM2 vocab) gives 16 tree levels, ~50k comparators.
For deeper pipelining (e.g. > 200 MHz target) the caller should insert
pipeline registers between every few levels — left as a follow-up.
"""
from __future__ import annotations

from textwrap import dedent

from ..core import Gate, RawSubmodule


def argmax_module_name(K: int, abits: int) -> str:
    return f"argmax_K{K}_a{abits}"


def argmax_block(
    *, K: int, abits: int, module_suffix: str = "",
) -> RawSubmodule:
    if K < 2:
        raise ValueError("K must be >= 2")
    idx_bits = max(1, (K - 1).bit_length())
    base = argmax_module_name(K, abits)
    name = base + (f"_{module_suffix}" if module_suffix else "")

    # Generate the tree using nested generate-for blocks. Level 0: K
    # candidates. Each level halves to ceil(prev/2). Last level: 1 candidate
    # = the answer.
    levels: list[int] = [K]
    while levels[-1] > 1:
        levels.append((levels[-1] + 1) // 2)
    n_levels = len(levels) - 1

    # Per-level wire arrays for value and index.
    decls: list[str] = []
    for L in range(n_levels + 1):
        decls.append(
            f"  wire signed [{abits-1}:0] level_{L}_val [0:{levels[L]-1}];"
        )
        decls.append(
            f"  wire        [{idx_bits-1}:0] level_{L}_idx [0:{levels[L]-1}];"
        )

    # Level 0 inputs: unpack x_packed and assign default indices.
    init_blocks: list[str] = []
    for i in range(K):
        init_blocks.append(
            f"  assign level_0_val[{i}] = "
            f"$signed(x_packed[{(i+1)*abits - 1}:{i*abits}]);"
        )
        init_blocks.append(
            f"  assign level_0_idx[{i}] = {idx_bits}'d{i};"
        )

    # Each subsequent level: pairwise comparisons.
    cmp_blocks: list[str] = []
    for L in range(1, n_levels + 1):
        prev = levels[L - 1]
        cur = levels[L]
        for j in range(cur):
            a = 2 * j
            b = 2 * j + 1
            if b < prev:
                cmp_blocks.append(
                    f"  assign level_{L}_val[{j}] = "
                    f"(level_{L-1}_val[{a}] >= level_{L-1}_val[{b}]) "
                    f"? level_{L-1}_val[{a}] : level_{L-1}_val[{b}];"
                )
                cmp_blocks.append(
                    f"  assign level_{L}_idx[{j}] = "
                    f"(level_{L-1}_val[{a}] >= level_{L-1}_val[{b}]) "
                    f"? level_{L-1}_idx[{a}] : level_{L-1}_idx[{b}];"
                )
            else:
                # odd-numbered last element: pass through
                cmp_blocks.append(
                    f"  assign level_{L}_val[{j}] = level_{L-1}_val[{a}];"
                )
                cmp_blocks.append(
                    f"  assign level_{L}_idx[{j}] = level_{L-1}_idx[{a}];"
                )

    text = dedent(f"""\
        // Generated by safetensors2verilog.blocks.argmax.
        // Combinational argmax over K = {K} signed {abits}-bit elements.
        // Tournament tree, {n_levels} comparison levels, {idx_bits}-bit output index.

        `default_nettype none

        module {name} (
          input  wire signed [{K*abits-1}:0]  x_packed,
          output wire        [{idx_bits-1}:0] argmax_idx
        );
        """) + "\n".join(decls) + "\n\n" + "\n".join(init_blocks) + "\n\n" + \
        "\n".join(cmp_blocks) + dedent(f"""

          assign argmax_idx = level_{n_levels}_idx[0];
        endmodule

        `default_nettype wire
        """)

    return RawSubmodule(top=name, text=text)


def argmax_invoke(
    *,
    instance_name: str,
    parent_x_packed: str,
    K: int,
    abits: int,
    idx_signal: str | None = None,
) -> tuple[RawSubmodule, list[Gate]]:
    sub = argmax_block(K=K, abits=abits)
    if idx_signal is None:
        idx_signal = f"{instance_name}_idx"
    idx_bits = max(1, (K - 1).bit_length())
    gates = [
        Gate(
            name=idx_signal, kind="instance",
            inputs=[parent_x_packed],
            attrs={
                "module_name": sub.top, "instance_name": instance_name,
                "input_ports": ["x_packed"],
                "output_port": "argmax_idx",
            },
            output_width=idx_bits, output_signed=False,
        ),
    ]
    return sub, gates
