"""Multi-head attention with internal KV cache (autoregressive form).

One token at a time. On ``start``, with the current ``position`` and the
projected Q (H*D), K (KV*D), V (KV*D), the block:

  1. Writes the new K and V rows into the internal caches at row ``position``.
  2. For each Q head h (sequentially):
     a. Walks (k_pos in 0..MAX_SEQ-1, d in 0..D-1), accumulating
        score[k_pos] += Q[h, d] * K_cache[head_kv(h), k_pos, d].
        score >>= score_shift after the d loop completes.
     b. Builds the causal mask (k_pos <= position) and runs the existing
        ``softmax_block`` over the score buffer.
     c. Walks (k_pos, d) again, accumulating
        vout_acc[d] += softmax[k_pos] * V_cache[head_kv(h), k_pos, d]
        into a per-dim accumulator file.
     d. Walks d once more, saturating vout_acc[d] >> out_shift into
        out_buf[h*D + d].
  3. After all H heads, asserts ``done`` with ``out_packed`` valid.

The KV mems are inline so the block can use combinational read (eliminates
the 2-cycle synchronous-read pipeline that complicates the score / V
loops). For BRAM-backed SmolLM2-scale inference the ``ram_style = "block"``
pragma still applies; Vivado will pick LUTRAM or BRAM based on size.

Cycle count per token, all H heads, for fixed MAX_SEQ:
  ~ H * (2*MAX_SEQ*D + 3*MAX_SEQ + 5 + D) + 6
"""
from __future__ import annotations

from textwrap import dedent

from ..core import Gate, RawSubmodule
from .softmax import softmax_block


def attention_module_name(
    H: int, KV: int, D: int, max_seq: int, abits: int,
) -> str:
    return f"mha_step_H{H}_KV{KV}_D{D}_S{max_seq}_a{abits}"


def attention_step_block(
    *,
    num_q_heads: int,
    num_kv_heads: int,
    head_dim: int,
    max_seq: int,
    abits: int = 8,
    score_bits: int | None = None,
    softmax_obits: int = 8,
    out_abits: int | None = None,
    score_shift: int = 0,
    out_shift: int = 8,
    softmax_kwargs: dict | None = None,
    module_suffix: str = "",
) -> tuple[RawSubmodule, list[RawSubmodule]]:
    """One-token autoregressive multi-head attention with internal KV cache.

    Returns ``(attention_submodule, [softmax_submodule, exp_submodule])``.
    The KV mems are inlined into the attention module; no separate cache
    submodule.
    """
    H, KV, D = num_q_heads, num_kv_heads, head_dim
    if H % KV != 0:
        raise ValueError(
            f"num_q_heads={H} must be divisible by num_kv_heads={KV}"
        )
    group = H // KV
    if max_seq < 1:
        raise ValueError("max_seq must be >= 1")
    if D < 1:
        raise ValueError("head_dim must be >= 1")
    if out_abits is None:
        out_abits = abits
    if score_bits is None:
        score_bits = 2 * abits + max(1, D.bit_length()) + 4
    softmax_kwargs = softmax_kwargs or {}

    pos_bits = max(1, (max_seq - 1).bit_length() + 1)
    head_idx_bits = max(1, (H - 1).bit_length() + 1) if H > 1 else 1
    kpos_idx_bits = max(1, (max_seq - 1).bit_length() + 1) if max_seq > 1 else 1
    d_idx_bits = max(1, (D - 1).bit_length() + 1) if D > 1 else 1
    h_kv_bits = max(1, (KV - 1).bit_length()) if KV > 1 else 1

    base = attention_module_name(H, KV, D, max_seq, abits)
    name = base + (f"_{module_suffix}" if module_suffix else "")

    sm, exp = softmax_block(
        K=max_seq, abits=score_bits, obits=softmax_obits, **softmax_kwargs,
    )

    qk_prod_bits = 2 * abits + 4
    score_acc_bits = score_bits + 4   # extra headroom before final shift
    sm_v_prod_bits = abits + softmax_obits + 2
    vout_acc_bits = max(
        sm_v_prod_bits + max(1, max_seq.bit_length()), out_abits + out_shift + 2
    )

    out_lo = -(1 << (out_abits - 1))
    out_hi = (1 << (out_abits - 1)) - 1

    k_row_bits = KV * D * abits
    v_row_bits = KV * D * abits

    text = dedent(f"""\
        // Generated by safetensors2verilog.blocks.attention.
        // Single-token multi-head attention with internal (inline) KV cache.
        //   H = {H}, KV = {KV}, group = {group}, D = {D}, MAX_SEQ = {max_seq}
        //   abits = {abits}, score_bits = {score_bits}, softmax_obits = {softmax_obits},
        //   out_abits = {out_abits}, score_shift = {score_shift}, out_shift = {out_shift}

        `default_nettype none

        module {name} (
          input  wire                                    clk,
          input  wire                                    rst,
          input  wire                                    start,
          input  wire        [{pos_bits-1}:0]             position,
          input  wire signed [{H*D*abits-1}:0]            q_packed,
          input  wire signed [{KV*D*abits-1}:0]           k_new_packed,
          input  wire signed [{KV*D*abits-1}:0]           v_new_packed,
          output wire                                    done,
          output wire signed [{H*D*out_abits-1}:0]        out_packed
        );

          // ----- FSM states -----
          localparam [3:0] STATE_IDLE          = 4'd0;
          localparam [3:0] STATE_WRITE_CACHE   = 4'd1;
          localparam [3:0] STATE_SCORE         = 4'd2;
          localparam [3:0] STATE_SCORE_FINISH  = 4'd3;
          localparam [3:0] STATE_SOFTMAX_START = 4'd4;
          localparam [3:0] STATE_SOFTMAX_WAIT  = 4'd5;
          localparam [3:0] STATE_VOUT          = 4'd6;
          localparam [3:0] STATE_VOUT_EMIT     = 4'd7;
          localparam [3:0] STATE_HEAD_NEXT     = 4'd8;
          localparam [3:0] STATE_DONE          = 4'd9;

          reg [3:0] state;

          reg [{head_idx_bits-1}:0]  head_idx;
          reg [{kpos_idx_bits-1}:0]  kpos_idx;
          reg [{d_idx_bits-1}:0]     d_idx;
          reg [{pos_bits-1}:0]       pos_latched;

          // ----- KV mems (inline, async read) -----
          (* ram_style = "block" *)
          reg [{k_row_bits-1}:0] k_mem [0:{max_seq-1}];
          (* ram_style = "block" *)
          reg [{v_row_bits-1}:0] v_mem [0:{max_seq-1}];
          reg                     cache_we;
          reg [{pos_bits-1}:0]    cache_w_pos;
          reg [{kpos_idx_bits-1}:0] cache_r_pos;

          // Zero-init mems so unused (masked) k_pos rows don't propagate X
          // through softmax's compares. Vivado / Quartus honour initial
          // blocks for BRAM init; iverilog simulates them at t=0.
          integer mem_init_i;
          initial begin
            for (mem_init_i = 0; mem_init_i < {max_seq};
                 mem_init_i = mem_init_i + 1) begin
              k_mem[mem_init_i] = 0;
              v_mem[mem_init_i] = 0;
            end
          end

          always @(posedge clk) begin
            if (cache_we) begin
              k_mem[cache_w_pos] <= k_new_packed;
              v_mem[cache_w_pos] <= v_new_packed;
            end
          end

          wire [{k_row_bits-1}:0] k_row = k_mem[cache_r_pos];
          wire [{v_row_bits-1}:0] v_row = v_mem[cache_r_pos];

          // ----- Q, K, V indexing for current (head, k_pos, d) -----
          wire [{h_kv_bits-1}:0] h_kv = head_idx / {group};

          wire signed [{abits-1}:0] q_now =
            $signed(q_packed[(head_idx * {D} + d_idx) * {abits} +: {abits}]);
          wire signed [{abits-1}:0] k_now =
            $signed(k_row[(h_kv * {D} + d_idx) * {abits} +: {abits}]);
          wire signed [{abits-1}:0] v_now =
            $signed(v_row[(h_kv * {D} + d_idx) * {abits} +: {abits}]);

          // ----- Score computation -----
          reg signed [{score_acc_bits-1}:0] score_acc;
          reg signed [{score_bits-1}:0]     score_buf [0:{max_seq-1}];
          reg [{max_seq-1}:0]               mask_buf;

          // Clear score_buf and out_buf at sim start so unmasked entries
          // don't pick up X bits before the first SCORE pass.
          integer scratch_init_i;
          initial begin
            for (scratch_init_i = 0; scratch_init_i < {max_seq};
                 scratch_init_i = scratch_init_i + 1)
              score_buf[scratch_init_i] = 0;
          end

          // ----- Softmax sub-instance -----
          wire signed [{max_seq*score_bits-1}:0] softmax_x_packed;
          genvar gpack;
          generate
            for (gpack = 0; gpack < {max_seq}; gpack = gpack + 1) begin: sm_pack
              assign softmax_x_packed[gpack*{score_bits} +: {score_bits}] =
                score_buf[gpack];
            end
          endgenerate

          reg                                       softmax_start;
          wire                                      softmax_done;
          wire [{max_seq*softmax_obits-1}:0]         softmax_y_packed;

          {sm.top} sm_inst (
            .clk(clk), .rst(rst), .start(softmax_start),
            .x_packed(softmax_x_packed), .mask(mask_buf),
            .done(softmax_done), .y_packed(softmax_y_packed)
          );

          // softmax_y[kpos_idx], unsigned softmax_obits
          wire [{softmax_obits-1}:0] sm_now =
            softmax_y_packed[kpos_idx*{softmax_obits} +: {softmax_obits}];

          // ----- V accumulator file (per d, per current head) -----
          reg signed [{vout_acc_bits-1}:0] vout_acc [0:{D-1}];

          // ----- Output buffer -----
          reg signed [{out_abits-1}:0] out_buf [0:{H*D-1}];
          genvar gout;
          generate
            for (gout = 0; gout < {H*D}; gout = gout + 1) begin: out_pack
              assign out_packed[gout*{out_abits} +: {out_abits}] = out_buf[gout];
            end
          endgenerate

          // ----- Causal mask builder helper (combinational) -----
          // mask[k_pos] = (k_pos <= pos_latched). Built fresh per head in
          // STATE_SCORE_FINISH (it's actually the same for all heads but
          // the buffer is small).

          // ----- Main FSM -----
          integer init_i;
          always @(posedge clk or posedge rst) begin
            if (rst) begin
              state         <= STATE_IDLE;
              head_idx      <= 0;
              kpos_idx      <= 0;
              d_idx         <= 0;
              pos_latched   <= 0;
              score_acc     <= 0;
              cache_we      <= 0;
              cache_w_pos   <= 0;
              cache_r_pos   <= 0;
              softmax_start <= 0;
              mask_buf      <= 0;
              // Blocking inside for-loops: verilator-friendly array init.
              for (init_i = 0; init_i < {H*D}; init_i = init_i + 1)
                out_buf[init_i] = 0;
              for (init_i = 0; init_i < {D}; init_i = init_i + 1)
                vout_acc[init_i] = 0;
            end else begin
              cache_we      <= 0;
              softmax_start <= 0;

              case (state)
                STATE_IDLE: begin
                  if (start) begin
                    pos_latched <= position;
                    head_idx    <= 0;
                    kpos_idx    <= 0;
                    d_idx       <= 0;
                    cache_we    <= 1;
                    cache_w_pos <= position;
                    cache_r_pos <= 0;
                    state       <= STATE_WRITE_CACHE;
                  end
                end

                STATE_WRITE_CACHE: begin
                  // The write fires this cycle (cache_we already 1 on entry,
                  // de-asserted at the start of the next cycle). Move to the
                  // SCORE stage.
                  kpos_idx  <= 0;
                  d_idx     <= 0;
                  score_acc <= 0;
                  state     <= STATE_SCORE;
                end

                STATE_SCORE: begin
                  // Accumulate q_now * k_now into score_acc. Cache_r_pos is
                  // already pointed at kpos_idx (combinational read).
                  if (d_idx == {D-1}) begin
                    score_buf[kpos_idx] <=
                      ($signed(score_acc) + q_now * k_now) >>> {score_shift};
                    d_idx     <= 0;
                    score_acc <= 0;
                    if (kpos_idx == {max_seq-1}) begin
                      state <= STATE_SCORE_FINISH;
                    end else begin
                      kpos_idx    <= kpos_idx + 1'b1;
                      cache_r_pos <= kpos_idx + 1'b1;
                    end
                  end else begin
                    score_acc <= score_acc + q_now * k_now;
                    d_idx     <= d_idx + 1'b1;
                  end
                end

                STATE_SCORE_FINISH: begin
                  // Causal mask: bits 0..pos_latched are 1, rest 0.
                  // Computed as (1 << (pos+1)) - 1, masked to max_seq bits.
                  // Single NBA so verilator accepts this and the reset
                  // path's NBA together.
                  mask_buf <=
                    (({{{max_seq}{{1'b1}}}} >> ({max_seq} - 1 - pos_latched))
                     & {{{max_seq}{{1'b1}}}});
                  state <= STATE_SOFTMAX_START;
                end

                STATE_SOFTMAX_START: begin
                  softmax_start <= 1;
                  state         <= STATE_SOFTMAX_WAIT;
                end

                STATE_SOFTMAX_WAIT: begin
                  if (softmax_done) begin
                    kpos_idx    <= 0;
                    d_idx       <= 0;
                    cache_r_pos <= 0;
                    // Blocking inside for-loop: verilator-friendly array reset.
                    for (init_i = 0; init_i < {D}; init_i = init_i + 1)
                      vout_acc[init_i] = 0;
                    state <= STATE_VOUT;
                  end
                end

                STATE_VOUT: begin
                  // vout_acc[d_idx] += sm_now * v_now (both treated as
                  // signed; sm_now is unsigned in [0, 2^softmax_obits-1] but
                  // we cast through a leading 0 to keep arithmetic signed).
                  vout_acc[d_idx] <=
                    vout_acc[d_idx] + $signed({{1'b0, sm_now}}) * v_now;
                  if (d_idx == {D-1}) begin
                    d_idx <= 0;
                    if (kpos_idx == {max_seq-1}) begin
                      kpos_idx <= 0;
                      d_idx    <= 0;
                      state    <= STATE_VOUT_EMIT;
                    end else begin
                      kpos_idx    <= kpos_idx + 1'b1;
                      cache_r_pos <= kpos_idx + 1'b1;
                    end
                  end else begin
                    d_idx <= d_idx + 1'b1;
                  end
                end

                STATE_VOUT_EMIT: begin
                  // Saturate vout_acc[d_idx] >>> out_shift into out_buf
                  begin: emit_step
                    reg signed [{vout_acc_bits-1}:0] shifted;
                    shifted = vout_acc[d_idx] >>> {out_shift};
                    out_buf[head_idx * {D} + d_idx] <=
                      (shifted > {out_hi})    ? {out_abits}'sd{out_hi}
                    : (shifted < ({out_lo})) ? -{out_abits}'sd{abs(out_lo)}
                    : shifted[{out_abits-1}:0];
                  end
                  if (d_idx == {D-1}) begin
                    d_idx <= 0;
                    state <= STATE_HEAD_NEXT;
                  end else begin
                    d_idx <= d_idx + 1'b1;
                  end
                end

                STATE_HEAD_NEXT: begin
                  if (head_idx == {H-1}) begin
                    state <= STATE_DONE;
                  end else begin
                    head_idx    <= head_idx + 1'b1;
                    kpos_idx    <= 0;
                    d_idx       <= 0;
                    score_acc   <= 0;
                    cache_r_pos <= 0;
                    state       <= STATE_SCORE;
                  end
                end

                STATE_DONE:  state <= STATE_IDLE;
                default:     state <= STATE_IDLE;
              endcase
            end
          end

          assign done = (state == STATE_DONE);

        endmodule

        `default_nettype wire
        """)

    return RawSubmodule(top=name, text=text), [sm, exp]


def attention_step_invoke(
    *,
    instance_name: str,
    parent_clk: str, parent_rst: str, parent_start: str,
    parent_position: str,
    parent_q_packed: str, parent_k_new_packed: str, parent_v_new_packed: str,
    num_q_heads: int, num_kv_heads: int, head_dim: int, max_seq: int,
    abits: int = 8,
    score_bits: int | None = None,
    softmax_obits: int = 8,
    out_abits: int | None = None,
    score_shift: int = 0,
    out_shift: int = 8,
    softmax_kwargs: dict | None = None,
    out_signal: str | None = None,
    done_signal: str | None = None,
) -> tuple[list[RawSubmodule], list[Gate]]:
    sub, deps = attention_step_block(
        num_q_heads=num_q_heads, num_kv_heads=num_kv_heads,
        head_dim=head_dim, max_seq=max_seq, abits=abits,
        score_bits=score_bits, softmax_obits=softmax_obits,
        out_abits=out_abits or abits,
        score_shift=score_shift, out_shift=out_shift,
        softmax_kwargs=softmax_kwargs,
    )
    if out_signal is None: out_signal = f"{instance_name}_out_packed"
    if done_signal is None: done_signal = f"{instance_name}_done"
    out_w = num_q_heads * head_dim * (out_abits or abits)
    gates = [
        Gate(name=done_signal, kind="extern_wire", output_width=1),
        Gate(
            name=out_signal, kind="instance",
            inputs=[parent_clk, parent_rst, parent_start, parent_position,
                    parent_q_packed, parent_k_new_packed, parent_v_new_packed],
            attrs={
                "module_name": sub.top, "instance_name": instance_name,
                "input_ports": ["clk", "rst", "start", "position",
                                "q_packed", "k_new_packed", "v_new_packed"],
                "output_port": "out_packed",
                "extra_output_ports": [("done", done_signal)],
            },
            output_width=out_w, output_signed=True,
        ),
    ]
    return [sub] + deps, gates
