"""Token embedding lookup.

A V x H ROM addressed by token id, returning H signed values per lookup.
For SmolLM2 the embed table is 49152 x 576 = 28M params at int8 = 28 MB,
which exceeds typical FPGA on-chip RAM. Two emission modes:

  inline_init=True  : weights baked into the module via ``initial begin``
                      blocks. Self-contained but verbose. Practical for
                      small vocabularies (test fixtures, vocab <= 1024).
  inline_init=False : emit a ``$readmemh(<name>.hex, ...)`` declaration
                      and a sidecar ``.hex`` file via RawSubmodule.sidecar_files.
                      Required for SmolLM2-scale tables.

Output is a packed bus of H * abits signed bits.
"""
from __future__ import annotations

from textwrap import dedent

from ..core import Gate, RawSubmodule


def embedding_module_name(V: int, H: int, abits: int) -> str:
    return f"embedding_V{V}_H{H}_a{abits}"


def _signed_mask(value: int, width: int) -> int:
    return value & ((1 << width) - 1)


def embedding_block(
    *,
    V: int,
    H: int,
    abits: int,
    weights: list[list[int]],
    inline_init: bool | None = None,
    chunked: bool | None = None,
    chunk_max_bits: int = 36864,
    chunk_max_depth: int = 2048,
    module_suffix: str = "",
) -> RawSubmodule:
    """V tokens, H-dim embedding. ``weights`` is V rows of H signed ints in ``abits``.

    When ``chunked`` is ``True`` (or ``None`` and ``V * H * abits`` exceeds
    ``chunk_max_bits * chunk_max_depth``), the row storage is split into
    BRAM-friendly per-(row_bank, col_bank) banks via
    ``safetensors2verilog.bram_chunk.emit_chunked_rom``. This is the path
    the SmolLM2-scale embedding (49152 x 576 x 8 = 226 Mbits) needs to
    avoid ``synth_xilinx``'s "no valid mapping found".
    """
    if len(weights) != V:
        raise ValueError(f"weights has {len(weights)} rows, expected V={V}")
    for r, row in enumerate(weights):
        if len(row) != H:
            raise ValueError(f"row {r} has length {len(row)}, expected H={H}")

    if inline_init is None:
        inline_init = (V * H) <= 4096
    if chunked is None:
        chunked = (V * H * abits) > (chunk_max_bits * chunk_max_depth)

    base = embedding_module_name(V, H, abits)
    name = base + (f"_{module_suffix}" if module_suffix else "")
    addr_bits = max(1, (V - 1).bit_length())

    sidecar_files: dict[str, str] = {}

    if chunked:
        # Chunked path: pack each row into a single H*abits-wide value
        # and feed (V, H*abits) into emit_chunked_rom. The address splits
        # into row-bank selector + per-bank-address; the result is a
        # row of H*abits bits we expose as ``hidden_packed``.
        from ..bram_chunk import emit_chunked_rom, pick_chunking
        row_width = H * abits
        cd, cb, n_row, n_col = pick_chunking(
            V, row_width,
            max_bram_bits=chunk_max_bits,
            max_bram_depth=chunk_max_depth,
        )
        # Pack each row into a single row_width-wide int.
        packed_rows: list[int] = []
        for v in range(V):
            packed = 0
            for j in range(H):
                bits = _signed_mask(weights[v][j], abits)
                packed |= bits << (j * abits)
            packed_rows.append(packed)
        body = emit_chunked_rom(
            "rom", packed_rows, depth=V, width=row_width,
            chunk_depth=cd, chunk_bits=cb, addr_signal="token_id",
        )
        text = (
            "// Generated by safetensors2verilog.blocks.embedding.\n"
            f"// Chunked-ROM token embedding. V = {V}, H = {H}, "
            f"abits = {abits}.\n"
            f"// chunk_depth = {cd}, chunk_bits = {cb}, "
            f"row_banks = {n_row}, col_banks = {n_col}.\n"
            "\n"
            "`default_nettype none\n"
            "\n"
            f"module {name} (\n"
            f"  input  wire [{addr_bits-1}:0]            token_id,\n"
            f"  output wire signed [{row_width-1}:0]     hidden_packed\n"
            ");\n"
            f"{body}\n"
            "  assign hidden_packed = rom;\n"
            "endmodule\n"
            "\n"
            "`default_nettype wire\n"
        )
        return RawSubmodule(top=name, text=text, sidecar_files={})

    if inline_init:
        rom_init_lines: list[str] = []
        for v in range(V):
            packed = 0
            for j in range(H):
                bits = _signed_mask(weights[v][j], abits)
                packed |= bits << (j * abits)
            rom_init_lines.append(
                f"    rom[{v}] = {H * abits}'h{packed:x};"
            )
        rom_init = "\n".join(rom_init_lines)
        init_block = f"""\
          initial begin
        {rom_init}
          end"""
        rom_decl = (
            f'  (* ram_style = "block" *)\n'
            f"  reg [{H*abits - 1}:0] rom [0:{V - 1}];"
        )
        read_expr = "rom[token_id]"
    else:
        # Flat layout: one element per memory cell. Avoids the wide-row
        # packing that would do 28M big-int shifts on SmolLM2-scale embeds.
        hex_filename = f"{name}_rom.hex"
        mask = (1 << abits) - 1
        try:
            import numpy as np
            arr = (np.asarray(weights, dtype=np.int64) & mask).reshape(-1)
            # Fast hex via numpy: format each element with the C printf-like
            # vectorisation. ``np.base_repr`` is per-element; faster path
            # is to use ``numpy.char`` after encoding to ascii. For 28M
            # elements ``["%x" % v for v in arr]`` runs in ~10 seconds and
            # is portable; that's the bottleneck we accept.
            hex_text = "\n".join("%x" % int(v) for v in arr)
        except ImportError:
            hex_text = "\n".join(
                "%x" % (weights[v][j] & mask)
                for v in range(V) for j in range(H)
            )
        sidecar_files[hex_filename] = hex_text + "\n"
        init_block = f'  initial $readmemh("{hex_filename}", rom_flat);'
        rom_decl = (
            f'  (* ram_style = "block" *)\n'
            f"  reg [{abits - 1}:0] rom_flat [0:{V*H - 1}];"
        )
        # combinational read of row[token_id]: pack H elements
        read_expr = None   # handled below via generate-for

    if inline_init:
        body_after_init = f"""\
          assign hidden_packed = {read_expr};
        """
    else:
        body_after_init = (
            "  genvar gj;\n"
            "  generate\n"
            "    for (gj = 0; gj < " + str(H) + "; gj = gj + 1) begin: pack\n"
            f"      assign hidden_packed[gj*{abits} +: {abits}] =\n"
            f"        rom_flat[token_id * {H} + gj];\n"
            "    end\n"
            "  endgenerate\n"
        )

    text = dedent(f"""\
        // Generated by safetensors2verilog.blocks.embedding.
        // Token embedding ROM. V = {V}, H = {H}, abits = {abits}.
        // Total weight bits = V*H*abits = {V*H*abits}.
        // Init mode: {'inline' if inline_init else 'sidecar hex file (flat)'}

        `default_nettype none

        module {name} (
          input  wire [{addr_bits-1}:0]            token_id,
          output wire signed [{H*abits-1}:0]       hidden_packed
        );
        """) + rom_decl + "\n" + init_block + "\n\n" + body_after_init + dedent("""\

        endmodule

        `default_nettype wire
        """)

    return RawSubmodule(top=name, text=text, sidecar_files=sidecar_files)


def embedding_invoke(
    *,
    instance_name: str,
    parent_token_signal: str,
    V: int,
    H: int,
    abits: int,
    weights: list[list[int]],
    inline_init: bool | None = None,
    y_signal: str | None = None,
) -> tuple[RawSubmodule, list[Gate]]:
    sub = embedding_block(
        V=V, H=H, abits=abits, weights=weights, inline_init=inline_init,
    )
    if y_signal is None:
        y_signal = f"{instance_name}_hidden_packed"
    gates = [
        Gate(
            name=y_signal, kind="instance",
            inputs=[parent_token_signal],
            attrs={
                "module_name": sub.top, "instance_name": instance_name,
                "input_ports": ["token_id"],
                "output_port": "hidden_packed",
            },
            output_width=H * abits, output_signed=True,
        ),
    ]
    return sub, gates
