"""LUT-based fixed-point exp.

For softmax we need ``exp(x - max(x))`` over inputs in (-inf, 0]. The LUT
covers a configurable range like [-16, 0] and pins values below the lower
clamp to 0 (which exp(-16) ~= 1.1e-7 is essentially anyway).

Output is unsigned ``out_bits`` Q0.``out_bits``: exp(0) = 1.0 maps to
``2**out_bits - 1``, exp(-16) maps to ~0.

Default: 8-bit signed input over [-16, 0) (Q4.4 with offset, see below),
8-bit unsigned output. 256 bytes per instance.

For finer accuracy use 12-bit signed input (4096 entries x 16-bit = 8 KB)
or do range reduction (split x into integer and fractional parts; LUT only
the fractional part, multiply by precomputed exp(integer) constants).
"""
from __future__ import annotations

import math
from textwrap import dedent

from ..core import Gate, RawSubmodule


def exp_module_name(in_bits: int, out_bits: int, in_q_frac_bits: int) -> str:
    return f"exp_lut_in{in_bits}f{in_q_frac_bits}_out{out_bits}"


def exp_block(
    *,
    in_bits: int = 8,
    out_bits: int = 16,
    in_q_frac_bits: int = 4,
    in_clamp: tuple[float, float] = (-16.0, 0.0),
    module_suffix: str = "",
) -> RawSubmodule:
    """Combinational exp LUT for softmax (input typically <= 0).

    in_bits:        signed input width
    out_bits:       unsigned output width (Q0.out_bits)
    in_q_frac_bits: fractional bits of the input
    in_clamp:       clamp (lo, hi) applied before lookup
    """
    if in_bits < 2 or out_bits < 2:
        raise ValueError("bit widths too small")
    n_entries = 1 << in_bits
    out_max = (1 << out_bits) - 1

    base = exp_module_name(in_bits, out_bits, in_q_frac_bits)
    name = base + (f"_{module_suffix}" if module_suffix else "")

    lut: list[int] = []
    for raw in range(n_entries):
        if raw & (1 << (in_bits - 1)):
            sint = raw - (1 << in_bits)
        else:
            sint = raw
        x = sint / (1 << in_q_frac_bits)
        x = max(in_clamp[0], min(in_clamp[1], x))
        v = math.exp(x)
        # exp(0) = 1.0 -> out_max; smaller exp -> smaller integer
        out_int = max(0, min(out_max, round(v * out_max)))
        lut.append(out_int)

    init_lines = "\n".join(
        f"    rom[{i}] = {out_bits}'h{lut[i]:x};" for i in range(n_entries)
    )
    text = dedent(f"""\
        // Generated by safetensors2verilog.blocks.exp.
        // LUT-based exp. in_bits={in_bits} signed, out_bits={out_bits} unsigned.
        // exp(0) = 1.0 -> y = {out_max}; exp(in_clamp_lo) ~= 0 -> y = 0.
        // ROM size: {n_entries} x {out_bits} bits.

        `default_nettype none

        module {name} (
          input  wire signed [{in_bits-1}:0] x,
          output wire        [{out_bits-1}:0] y
        );
          (* ram_style = "block" *)
          reg [{out_bits-1}:0] rom [0:{n_entries-1}];
          initial begin
        {init_lines}
          end
          assign y = rom[x[{in_bits-1}:0]];
        endmodule

        `default_nettype wire
        """)
    return RawSubmodule(top=name, text=text)


def exp_invoke(
    *,
    instance_name: str,
    parent_x_signal: str,
    in_bits: int = 8,
    out_bits: int = 16,
    in_q_frac_bits: int = 4,
    in_clamp: tuple[float, float] = (-16.0, 0.0),
    y_signal: str | None = None,
) -> tuple[RawSubmodule, list[Gate]]:
    sub = exp_block(
        in_bits=in_bits, out_bits=out_bits,
        in_q_frac_bits=in_q_frac_bits, in_clamp=in_clamp,
    )
    if y_signal is None:
        y_signal = f"{instance_name}_y"
    gates = [
        Gate(
            name=y_signal,
            kind="instance",
            inputs=[parent_x_signal],
            attrs={
                "module_name": sub.top,
                "instance_name": instance_name,
                "input_ports": ["x"],
                "output_port": "y",
            },
            output_width=out_bits,
            output_signed=False,
        ),
    ]
    return sub, gates
