"""KV cache: writable BRAM for storing per-position K and V projections.

One instance per (layer, K|V), shared across the num_kv_heads heads in
that layer (the heads' head_dim slices live side-by-side in one wide
BRAM word). Position-indexed write port + position-indexed read port
(synchronous read so Vivado infers a true block RAM).

For SmolLM2: max_seq=8192, num_kv_heads=3, head_dim=64, abits=8 ->
each cache row is 3*64*8 = 1536 bits per layer. 8192 rows = 12 Mbit per
cache (K or V) per layer. Across 30 layers, K+V = 60 instances, total
720 Mbit ~ 90 MB. Fits a Stratix 10 MX with HBM, otherwise stream from
DDR.
"""
from __future__ import annotations

from textwrap import dedent

from ..core import Gate, RawSubmodule


def kv_cache_module_name(max_seq: int, row_bits: int) -> str:
    return f"kv_cache_S{max_seq}_R{row_bits}"


def kv_cache_block(
    *,
    max_seq: int,
    row_bits: int,
    module_suffix: str = "",
) -> RawSubmodule:
    """Single-port-per-direction writable BRAM.

    max_seq: number of rows (positions in the KV sequence).
    row_bits: width of each row (typically num_kv_heads * head_dim * abits).
    """
    if max_seq < 2:
        raise ValueError("max_seq must be >= 2")
    pos_bits = max(1, (max_seq - 1).bit_length())

    base = kv_cache_module_name(max_seq, row_bits)
    name = base + (f"_{module_suffix}" if module_suffix else "")

    text = dedent(f"""\
        // Generated by safetensors2verilog.blocks.kv_cache.
        // Per-layer K or V cache: max_seq = {max_seq} rows of {row_bits} bits.
        // Synchronous read, synchronous write. Vivado / Quartus infer BRAM.

        `default_nettype none

        module {name} (
          input  wire                            clk,
          input  wire        [{pos_bits-1}:0]    write_pos,
          input  wire        [{row_bits-1}:0]    write_data,
          input  wire                            write_en,
          input  wire        [{pos_bits-1}:0]    read_pos,
          output reg         [{row_bits-1}:0]    read_data
        );
          (* ram_style = "block" *)
          reg [{row_bits-1}:0] mem [0:{max_seq-1}];

          always @(posedge clk) begin
            if (write_en) mem[write_pos] <= write_data;
            read_data <= mem[read_pos];
          end

        endmodule

        `default_nettype wire
        """)

    return RawSubmodule(top=name, text=text)


def kv_cache_invoke(
    *,
    instance_name: str,
    parent_clk: str,
    parent_write_pos: str,
    parent_write_data: str,
    parent_write_en: str,
    parent_read_pos: str,
    max_seq: int,
    row_bits: int,
    read_data_signal: str | None = None,
) -> tuple[RawSubmodule, list[Gate]]:
    sub = kv_cache_block(max_seq=max_seq, row_bits=row_bits)
    if read_data_signal is None:
        read_data_signal = f"{instance_name}_read_data"
    gates = [
        Gate(
            name=read_data_signal, kind="instance",
            inputs=[parent_clk, parent_write_pos, parent_write_data,
                    parent_write_en, parent_read_pos],
            attrs={
                "module_name": sub.top, "instance_name": instance_name,
                "input_ports": ["clk", "write_pos", "write_data",
                                "write_en", "read_pos"],
                "output_port": "read_data",
            },
            output_width=row_bits, output_signed=False,
        ),
    ]
    return sub, gates
