"""LayerNorm: y = ((x - mean(x)) / sqrt(var(x) + eps)) * gamma + beta.

Same FSM as rms_norm but with two extra passes:
  - PASS_MEAN_SUM: K cycles, accumulate sum_x.
  - mean = sum_x / K computed once via shift (when K is power-of-2) or a
    multiply-by-recip otherwise.
  - PASS_ACCUM_DEV: K cycles, accumulate sum((x - mean)**2).
  - PASS_LOOKUP + PASS_NORM: as in rms_norm, plus a beta add at the end.

Bakes both gamma and beta as per-element ROMs. Caller chooses Q-format
shifts the same way as rms_norm.
"""
from __future__ import annotations

import math
from textwrap import dedent

from ..core import Gate, RawSubmodule
from .rsqrt import rsqrt_block


def layer_norm_module_name(K: int, abits: int, gbits: int, obits: int) -> str:
    return f"layer_norm_K{K}_a{abits}_g{gbits}_o{obits}"


def _signed_mask(value: int, width: int) -> int:
    return value & ((1 << width) - 1)


def layer_norm_block(
    *,
    K: int,
    gamma_int: list[int],
    beta_int: list[int],
    gamma_bits: int = 16,
    beta_bits: int = 16,
    abits: int = 8,
    obits: int = 8,
    eps: float = 1e-5,
    eps_q: int = 16,
    rsqrt_in_bits: int | None = None,
    rsqrt_out_bits: int = 16,
    rsqrt_out_frac_bits: int = 14,
    output_shift: int = 14,
    module_suffix: str = "",
) -> tuple[RawSubmodule, RawSubmodule]:
    """Build (layer_norm, rsqrt_lut).

    Returns the two RawSubmodules; caller appends both to graph.submodules.
    """
    if K < 1:
        raise ValueError("K must be >= 1")
    if len(gamma_int) != K:
        raise ValueError(f"gamma length {len(gamma_int)} != K={K}")
    if len(beta_int) != K:
        raise ValueError(f"beta length {len(beta_int)} != K={K}")

    sum_sq_bits = 2 * abits + max(1, K.bit_length()) + 4
    sum_x_bits = abits + max(1, K.bit_length()) + 1
    if rsqrt_in_bits is None:
        rsqrt_in_bits = sum_sq_bits + 4

    counter_bits = max(1, (K - 1).bit_length() + 1)

    eps_int = round(eps * (1 << eps_q))
    K_eps_int = K * eps_int

    # Mean = sum_x / K. We compute it as round(sum_x / K) inside the
    # always block via a synthesizable divide-by-constant. For K power-of-2
    # this is a shift; otherwise we precompute a Q-format reciprocal of K
    # and multiply.
    is_pow2 = (K & (K - 1)) == 0
    if is_pow2:
        mean_shift = K.bit_length() - 1
        mean_recip = 0
        mean_recip_bits = 1
    else:
        # Q1.16 reciprocal of K
        mean_shift = 16
        mean_recip = round((1 << mean_shift) / K)
        mean_recip_bits = 17

    base_name = layer_norm_module_name(K, abits, gamma_bits, obits)
    name = base_name + (f"_{module_suffix}" if module_suffix else "")

    rsqrt = rsqrt_block(
        in_bits=rsqrt_in_bits,
        out_bits=rsqrt_out_bits,
        out_frac_bits=rsqrt_out_frac_bits,
    )
    rsqrt_name = rsqrt.top

    gamma_init = "\n".join(
        f"    gamma_rom[{i}] = {gamma_bits}'h"
        f"{_signed_mask(gamma_int[i], gamma_bits):x};"
        for i in range(K)
    )
    beta_init = "\n".join(
        f"    beta_rom[{i}] = {beta_bits}'h"
        f"{_signed_mask(beta_int[i], beta_bits):x};"
        for i in range(K)
    )

    out_lo = -(1 << (obits - 1))
    out_hi = (1 << (obits - 1)) - 1

    # Centered x: x - mean (signed). Width grows by 1 bit.
    centered_bits = abits + 1

    # Mean computation lives in an intermediate ``mean_full`` wire whose
    # bits we slice into ``mean_latched``. (Verilog rejects a bit-select
    # on an unparenthesised compound expression like (a >>> n)[hi:lo].)
    if is_pow2:
        mean_full_bits = sum_x_bits
        mean_full_decl = (
            f"wire signed [{mean_full_bits-1}:0] mean_full = "
            f"sum_x_signed >>> {mean_shift};"
        )
    else:
        mean_full_bits = sum_x_bits + mean_recip_bits
        mean_full_decl = (
            f"wire signed [{mean_full_bits-1}:0] mean_full = "
            f"(sum_x_signed * {mean_recip_bits}'sd{mean_recip}) "
            f">>> {mean_shift};"
        )

    text = dedent(f"""\
        // Generated by safetensors2verilog.blocks.layer_norm.
        // LayerNorm: y = ((x - mean) * gamma) * rsqrt(var + K*eps) + beta.
        //   K = {K}, abits = {abits}, gbits = {gamma_bits}, bbits = {beta_bits}, obits = {obits}
        //   eps = {eps:.3e}, output_shift = {output_shift}
        //   latency: 3K + 4 cycles per token

        `default_nettype none

        module {name} (
          input  wire                              clk,
          input  wire                              rst,
          input  wire                              start,
          input  wire signed [{K*abits-1}:0]        x_packed,
          output wire                              done,
          output wire signed [{K*obits-1}:0]        y_packed
        );

          localparam [2:0] STATE_IDLE       = 3'd0;
          localparam [2:0] STATE_MEAN_SUM   = 3'd1;
          localparam [2:0] STATE_ACCUM_DEV  = 3'd2;
          localparam [2:0] STATE_LOOKUP     = 3'd3;
          localparam [2:0] STATE_NORM       = 3'd4;
          localparam [2:0] STATE_DONE       = 3'd5;

          reg [2:0] state;
          reg [{counter_bits-1}:0] counter;
          wire counter_at_max = (counter == {K-1});

          always @(posedge clk or posedge rst) begin
            if (rst) begin
              state <= STATE_IDLE;
              counter <= 0;
            end else case (state)
              STATE_IDLE: begin
                counter <= 0;
                if (start) state <= STATE_MEAN_SUM;
              end
              STATE_MEAN_SUM:
                if (counter_at_max) begin state <= STATE_ACCUM_DEV; counter <= 0; end
                else counter <= counter + 1'b1;
              STATE_ACCUM_DEV:
                if (counter_at_max) begin state <= STATE_LOOKUP; counter <= 0; end
                else counter <= counter + 1'b1;
              STATE_LOOKUP: begin state <= STATE_NORM; counter <= 0; end
              STATE_NORM:
                if (counter_at_max) begin state <= STATE_DONE; counter <= 0; end
                else counter <= counter + 1'b1;
              STATE_DONE: state <= STATE_IDLE;
              default:    state <= STATE_IDLE;
            endcase
          end

          assign done = (state == STATE_DONE);

          // Activation buffer
          reg signed [{abits-1}:0] x_buf [0:{K-1}];
          integer i;
          always @(posedge clk) begin
            if (state == STATE_IDLE && start)
              for (i = 0; i < {K}; i = i + 1)
                x_buf[i] = $signed(x_packed[i*{abits} +: {abits}]);
          end

          wire signed [{abits-1}:0] x_now = x_buf[counter];

          // Pass 1: sum_x
          reg signed [{sum_x_bits-1}:0] sum_x;
          always @(posedge clk or posedge rst) begin
            if (rst) sum_x <= 0;
            else if (state == STATE_IDLE && start) sum_x <= 0;
            else if (state == STATE_MEAN_SUM)
              sum_x <= sum_x + x_now;
          end

          wire signed [{sum_x_bits-1}:0] sum_x_signed = sum_x;
          // Mean computed once at the end of MEAN_SUM, latched for use
          // throughout ACCUM_DEV and NORM.
          {mean_full_decl}
          reg signed [{centered_bits-1}:0] mean_latched;
          always @(posedge clk) begin
            if (state == STATE_MEAN_SUM && counter_at_max)
              mean_latched <= mean_full[{centered_bits-1}:0];
          end

          wire signed [{centered_bits}:0] x_centered =
            $signed({{x_now[{abits-1}], x_now}}) - $signed({{mean_latched[{centered_bits-1}], mean_latched}});

          // Pass 2: sum_sq of centered values. The square of a
          // (centered_bits+1)-bit signed value fits in 2*(centered_bits+1)
          // bits unsigned (it's always non-negative). Accumulate K of
          // them with log2(K) extra bits of headroom.
          reg [{sum_sq_bits-1}:0] sum_sq;
          wire signed [{2*(centered_bits+1)-1}:0] sq_full = x_centered * x_centered;
          wire [{2*(centered_bits+1)-1}:0] sq_unsigned = $unsigned(sq_full);
          always @(posedge clk or posedge rst) begin
            if (rst) sum_sq <= 0;
            else if (state == STATE_IDLE && start) sum_sq <= 0;
            else if (state == STATE_ACCUM_DEV)
              sum_sq <= sum_sq + sq_unsigned;
          end

          wire [{rsqrt_in_bits-1}:0] sum_sq_eps =
            sum_sq + {rsqrt_in_bits}'h{K_eps_int:x};

          wire [{rsqrt_out_bits-1}:0] rsqrt_val_comb;
          {rsqrt_name} rsqrt_inst (
            .x(sum_sq_eps),
            .y(rsqrt_val_comb)
          );

          reg [{rsqrt_out_bits-1}:0] rsqrt_val;
          always @(posedge clk) begin
            if (state == STATE_LOOKUP) rsqrt_val <= rsqrt_val_comb;
          end

          // Gamma + beta ROMs
          (* ram_style = "block" *)
          reg signed [{gamma_bits-1}:0] gamma_rom [0:{K-1}];
          (* ram_style = "block" *)
          reg signed [{beta_bits-1}:0] beta_rom [0:{K-1}];
          initial begin
        {gamma_init}
          end
          initial begin
        {beta_init}
          end
          wire signed [{gamma_bits-1}:0] gamma_now = gamma_rom[counter];
          wire signed [{beta_bits-1}:0]  beta_now  = beta_rom[counter];

          // Pass 3: y = (x_centered * gamma_now) * rsqrt_val >>> shift + beta
          wire signed [{centered_bits + gamma_bits + 1}:0] xg = x_centered * gamma_now;
          wire signed [{centered_bits + gamma_bits + rsqrt_out_bits + 2}:0] xgr =
            xg * $signed({{1'b0, rsqrt_val}});
          wire signed [{centered_bits + gamma_bits + rsqrt_out_bits + 2}:0] shifted =
            xgr >>> {output_shift};
          wire signed [{centered_bits + gamma_bits + rsqrt_out_bits + 3}:0] with_beta =
            shifted + beta_now;
          wire signed [{obits-1}:0] y_sat =
            (with_beta > {out_hi}) ? {obits}'sd{out_hi}
          : (with_beta < ({out_lo})) ? -{obits}'sd{abs(out_lo)}
          : with_beta[{obits-1}:0];

          reg signed [{obits-1}:0] y_buf [0:{K-1}];
          always @(posedge clk) begin
            if (state == STATE_NORM) y_buf[counter] <= y_sat;
          end

          genvar j;
          generate
            for (j = 0; j < {K}; j = j + 1) begin: pack
              assign y_packed[j*{obits} +: {obits}] = y_buf[j];
            end
          endgenerate

        endmodule

        `default_nettype wire
        """)

    return RawSubmodule(top=name, text=text), rsqrt
