"""Streaming-output matrix multiply.

The default ``matmul_seq`` keeps M parallel MAC units and emits all M outputs
after K cycles. At SmolLM2 lm_head scale (M=49152, K=576) that means 49152
weight ROMs + 49152 always blocks, which dominates iverilog parse time.

This block trades latency for area: one MAC unit shared across all M
outputs, walking j outer and i inner. Latency is M*K cycles instead of K,
but the Verilog text is small (one big weight ROM, one MAC, one FSM).
Output is a stream: ``y_valid`` rises for one cycle each time an output
element is ready, with ``j_idx`` indicating which output and ``y_value``
carrying the value. ``done`` rises after the M-th output.

For SmolLM2 lm_head (49152*576): 28M cycles per token = 280 ms at 100 MHz.
The downstream ``argmax_stream`` block tracks running max + index across
the stream and outputs the final next_token_id when ``done`` fires.

Resources per instance:
  - one M*K-entry weight ROM (sidecar hex, BRAM-friendly)
  - one K-entry activation buffer
  - one signed (act_bits + weight_bits)-bit multiplier
  - one out_bits accumulator
  - small FSM (2-bit state, j and i counters)
"""
from __future__ import annotations

from textwrap import dedent

from ..core import Gate, RawSubmodule


def matmul_streaming_module_name(
    M: int, K: int, weight_bits: int, act_bits: int, out_bits: int,
) -> str:
    return (
        f"matmul_stream_M{M}_K{K}_w{weight_bits}_a{act_bits}_o{out_bits}"
    )


def _signed_mask(value: int, width: int) -> int:
    return value & ((1 << width) - 1)


def matmul_streaming_block(
    weights: list[list[int]],
    *,
    weight_bits: int,
    act_bits: int,
    out_bits: int | None = None,
    biases: list[int] | None = None,
    module_suffix: str = "",
) -> RawSubmodule:
    """Streaming-output matmul. One MAC, M*K total cycles.

    Module ports:
      clk, rst, start
      x_packed[K*act_bits-1:0]      // input vector
      y_valid                        // 1-cycle pulse per output element
      j_idx[ceil(log2(M))-1:0]       // which output element
      y_value[out_bits-1:0]          // output value (signed)
      done                           // 1-cycle pulse after M-th output
    """
    M = len(weights)
    if M == 0:
        raise ValueError("weights must have at least one row")
    K = len(weights[0])
    for j, row in enumerate(weights):
        if len(row) != K:
            raise ValueError(f"row {j} has length {len(row)}, expected {K}")

    biases = list(biases) if biases is not None else [0] * M
    if len(biases) != M:
        raise ValueError(f"biases length {len(biases)} != M={M}")

    if out_bits is None:
        out_bits = (
            act_bits + weight_bits + max(1, (K - 1).bit_length()) + 1
        )

    base = matmul_streaming_module_name(M, K, weight_bits, act_bits, out_bits)
    name = base + (f"_{module_suffix}" if module_suffix else "")

    j_bits = max(1, (M - 1).bit_length() + 1)
    i_bits = max(1, (K - 1).bit_length() + 1)

    # Sidecar weight hex: M*K entries, row-major (j*K + i).
    hex_filename = f"{name}_rom.hex"
    hex_lines = []
    for j in range(M):
        for i in range(K):
            hex_lines.append(f"{_signed_mask(weights[j][i], weight_bits):x}")
    hex_text = "\n".join(hex_lines) + "\n"
    sidecar = {hex_filename: hex_text}

    # Bias ROM (small): one entry per output.
    bias_init = "\n".join(
        f"    bias_rom[{j}] = {out_bits}'h{_signed_mask(biases[j], out_bits):x};"
        for j in range(M)
    )

    text = dedent(f"""\
        // Generated by safetensors2verilog.blocks.matmul_stream.
        // Streaming-output matmul. M={M}, K={K}, w={weight_bits}, a={act_bits}, o={out_bits}.
        // One MAC, latency M*K = {M*K} cycles per token.

        `default_nettype none

        module {name} (
          input  wire                            clk,
          input  wire                            rst,
          input  wire                            start,
          input  wire signed [{K*act_bits - 1}:0] x_packed,
          output wire                            y_valid,
          output wire        [{j_bits - 1}:0]    j_idx,
          output wire signed [{out_bits - 1}:0]  y_value,
          output wire                            done
        );

          // ---- FSM ----
          localparam [1:0] STATE_IDLE    = 2'd0;
          localparam [1:0] STATE_COMPUTE = 2'd1;
          localparam [1:0] STATE_EMIT    = 2'd2;
          localparam [1:0] STATE_DONE    = 2'd3;

          reg [1:0] state;
          reg [{j_bits - 1}:0] j_reg;
          reg [{i_bits - 1}:0] i_reg;
          wire i_at_max = (i_reg == {K - 1});
          wire j_at_max = (j_reg == {M - 1});

          // ---- Activation buffer (latched on start) ----
          reg signed [{act_bits - 1}:0] x_buf [0:{K - 1}];
          integer ii;
          // Blocking inside for-loop: verilator-friendly array init.
          always @(posedge clk) begin
            if (state == STATE_IDLE && start)
              for (ii = 0; ii < {K}; ii = ii + 1)
                x_buf[ii] = $signed(x_packed[ii*{act_bits} +: {act_bits}]);
          end

          // ---- Weight ROM ----
          (* ram_style = "block" *)
          reg signed [{weight_bits - 1}:0] w_rom [0:{M*K - 1}];
          initial $readmemh("{hex_filename}", w_rom);

          // ---- Bias ROM ----
          (* ram_style = "block" *)
          reg signed [{out_bits - 1}:0] bias_rom [0:{M - 1}];
          initial begin
        {bias_init}
          end

          // ---- Combinational read of current weight + activation ----
          wire signed [{weight_bits - 1}:0] w_now =
            $signed(w_rom[j_reg * {K} + i_reg]);
          wire signed [{act_bits - 1}:0]    x_now = x_buf[i_reg];
          wire signed [{out_bits - 1}:0]    bias_now = bias_rom[j_reg];

          // ---- MAC accumulator ----
          reg signed [{out_bits - 1}:0] acc;

          always @(posedge clk or posedge rst) begin
            if (rst) begin
              state <= STATE_IDLE;
              j_reg <= 0;
              i_reg <= 0;
              acc   <= 0;
            end else case (state)
              STATE_IDLE: begin
                j_reg <= 0;
                i_reg <= 0;
                if (start) begin
                  state <= STATE_COMPUTE;
                  acc   <= bias_now;
                end
              end
              STATE_COMPUTE: begin
                acc <= acc + w_now * x_now;
                if (i_at_max) begin
                  state <= STATE_EMIT;
                end else begin
                  i_reg <= i_reg + 1'b1;
                end
              end
              STATE_EMIT: begin
                // y_valid asserted this cycle (combinational), advance j.
                if (j_at_max) begin
                  state <= STATE_DONE;
                end else begin
                  state <= STATE_COMPUTE;
                  j_reg <= j_reg + 1'b1;
                  i_reg <= 0;
                  acc   <= bias_rom[j_reg + 1'b1];
                end
              end
              STATE_DONE: state <= STATE_IDLE;
              default:    state <= STATE_IDLE;
            endcase
          end

          assign y_valid = (state == STATE_EMIT);
          assign j_idx   = j_reg;
          assign y_value = acc;
          assign done    = (state == STATE_DONE);

        endmodule

        `default_nettype wire
        """)

    return RawSubmodule(top=name, text=text, sidecar_files=sidecar)


def argmax_stream_module_name(M: int, abits: int) -> str:
    return f"argmax_stream_M{M}_a{abits}"


def argmax_stream_block(
    *,
    M: int,
    abits: int,
    module_suffix: str = "",
) -> RawSubmodule:
    """Streaming argmax: receives one (j_idx, y_value) per cycle when y_valid,
    tracks running maximum + its index, and asserts the final argmax_idx
    when ``done`` fires.

    Tiny resources: just a register file of size 1 (cur_max + cur_idx).
    """
    j_bits = max(1, (M - 1).bit_length() + 1)
    base = argmax_stream_module_name(M, abits)
    name = base + (f"_{module_suffix}" if module_suffix else "")

    text = dedent(f"""\
        // Generated by safetensors2verilog.blocks.matmul_stream.
        // Streaming argmax over a (j_idx, y_value) stream.
        // Resets on ``start``, latches running max each ``y_valid`` cycle,
        // exposes ``argmax_idx`` once ``done`` fires.

        `default_nettype none

        module {name} (
          input  wire                            clk,
          input  wire                            rst,
          input  wire                            start,
          input  wire                            y_valid,
          input  wire        [{j_bits - 1}:0]    j_idx,
          input  wire signed [{abits - 1}:0]     y_value,
          output reg         [{j_bits - 1}:0]    argmax_idx,
          output reg signed  [{abits - 1}:0]     argmax_value
        );

          always @(posedge clk or posedge rst) begin
            if (rst) begin
              argmax_idx   <= 0;
              argmax_value <= -{abits}'sd{(1 << (abits - 1)) - 1};
            end else if (start) begin
              argmax_idx   <= 0;
              argmax_value <= -{abits}'sd{(1 << (abits - 1)) - 1};
            end else if (y_valid && y_value > argmax_value) begin
              argmax_value <= y_value;
              argmax_idx   <= j_idx;
            end
          end

        endmodule

        `default_nettype wire
        """)
    return RawSubmodule(top=name, text=text)
