"""Per-channel integer requantisation (matmul accumulator -> activation bits).

Standard PTQ requantisation: ``y = sat(round((x * mul) >> shift))`` per
channel. ``mul`` and ``shift`` are picked offline so that the floating-
point dequantisation result rounds to the same integer that this block
produces for typical activation distributions.

Combinational: produces all K outputs in the same cycle the input is
presented. No state, no clock; the matmul block upstream supplies a
clock if its accumulator was registered.

Generalises across LLaMA / Qwen / Mistral / SmolLM2: every transformer
intermediate uses a chain of `matmul -> requantize -> next_op`.
"""
from __future__ import annotations

from textwrap import dedent

from ..core import Gate, RawSubmodule


def requantize_module_name(
    K: int, in_bits: int, out_bits: int, mul_bits: int,
) -> str:
    return f"requantize_K{K}_in{in_bits}_out{out_bits}_m{mul_bits}"


def requantize_block(
    *,
    K: int,
    in_bits: int,
    out_bits: int,
    muls: list[int],
    shifts: list[int],
    mul_bits: int = 16,
    module_suffix: str = "",
) -> RawSubmodule:
    """Per-channel requantize: y[j] = sat( (x[j] * muls[j]) >>> shifts[j] ).

    K:          number of channels (must equal len(muls), len(shifts))
    in_bits:    input bit width (signed); typically 32 from a matmul accumulator
    out_bits:   output bit width (signed); typically 8 for downstream activations
    muls:       per-channel signed integer multiplier in [-2^(mul_bits-1)+1,
                2^(mul_bits-1)-1]
    shifts:     per-channel arithmetic right-shift amount, non-negative.
    mul_bits:   bit width of the multiplier (signed). 16 fits typical PTQ
                scales; bump to 32 for very fine-grained calibration.
    """
    if len(muls) != K or len(shifts) != K:
        raise ValueError(
            f"len(muls)={len(muls)}, len(shifts)={len(shifts)}, expected K={K}"
        )

    base = requantize_module_name(K, in_bits, out_bits, mul_bits)
    name = base + (f"_{module_suffix}" if module_suffix else "")

    out_lo = -(1 << (out_bits - 1)) + 1
    out_hi = (1 << (out_bits - 1)) - 1
    mul_mask = (1 << mul_bits) - 1

    per_chan_blocks: list[str] = []
    for j in range(K):
        m = muls[j] & mul_mask
        s = int(shifts[j])
        if s < 0:
            raise ValueError(f"shift[{j}]={s} must be non-negative")
        per_chan_blocks.append(dedent(f"""\
          // -- channel {j} --
          wire signed [{in_bits + mul_bits - 1}:0] mulprod_{j} =
            $signed(x_packed[{(j+1)*in_bits - 1}:{j*in_bits}]) *
            $signed({mul_bits}'h{m:x});
          wire signed [{in_bits + mul_bits - 1}:0] shifted_{j} =
            mulprod_{j} >>> {s};
          assign y_packed[{(j+1)*out_bits - 1}:{j*out_bits}] =
            (shifted_{j} > {out_hi}) ? {out_bits}'sd{out_hi} :
            (shifted_{j} < ({out_lo})) ? -{out_bits}'sd{abs(out_lo)} :
            shifted_{j}[{out_bits-1}:0];
        """))

    body = "\n".join(per_chan_blocks)
    text = dedent(f"""\
        // Generated by safetensors2verilog.blocks.requantize.
        // Per-channel integer requantize: y = sat((x * mul) >>> shift)
        //   K = {K}, in_bits = {in_bits}, out_bits = {out_bits}, mul_bits = {mul_bits}

        `default_nettype none

        module {name} (
          input  wire signed [{K * in_bits - 1}:0]  x_packed,
          output wire signed [{K * out_bits - 1}:0] y_packed
        );

        {body}
        endmodule

        `default_nettype wire
        """)
    return RawSubmodule(top=name, text=text)


def requantize_invoke(
    *,
    instance_name: str,
    parent_x_signal: str,
    K: int,
    in_bits: int,
    out_bits: int,
    muls: list[int],
    shifts: list[int],
    y_signal: str | None = None,
    mul_bits: int = 16,
) -> tuple[RawSubmodule, list[Gate]]:
    """Build the (submodule, gates) for a requantize between two packed buses."""
    sub = requantize_block(
        K=K, in_bits=in_bits, out_bits=out_bits,
        muls=muls, shifts=shifts, mul_bits=mul_bits,
    )
    if y_signal is None:
        y_signal = f"{instance_name}_y_packed"
    gates = [
        Gate(
            name=y_signal,
            kind="instance",
            inputs=[parent_x_signal],
            attrs={
                "module_name": sub.top,
                "instance_name": instance_name,
                "input_ports": ["x_packed"],
                "output_port": "y_packed",
            },
            output_width=K * out_bits,
            output_signed=True,
        ),
    ]
    return sub, gates


def compute_mul_shift(
    fp_scale: float, *, mul_bits: int = 16,
) -> tuple[int, int]:
    """Pick (mul, shift) so that ``x * mul >> shift`` approximates ``x * fp_scale``.

    Returns the smallest shift such that ``mul = round(fp_scale * 2**shift)``
    fits in ``mul_bits`` signed. Works for both upscale (fp_scale > 1) and
    downscale (fp_scale < 1).
    """
    if fp_scale == 0:
        return 0, 0
    sign = 1 if fp_scale > 0 else -1
    s = abs(fp_scale)
    mul_max = (1 << (mul_bits - 1)) - 1
    # Find shift so that round(s * 2**shift) is just under mul_max
    shift = 0
    while s * (1 << shift) < mul_max // 2 and shift < 62:
        shift += 1
    mul = sign * round(s * (1 << shift))
    if abs(mul) > mul_max:
        # one bit too many; back off
        shift -= 1
        mul = sign * round(s * (1 << shift))
    return mul, shift
