"""RMSNorm: y = (x * gamma) * rsqrt(sum(x^2) + K*eps).

Sequential FSM, latency 2K+3 cycles per token. Architecture:

  IDLE:   latch x_packed on start.
  ACCUM:  K cycles, walk i=0..K-1, sum_sq += x_buf[i] * x_buf[i].
  LOOKUP: 1 cycle, rsqrt_val = rsqrt(sum_sq + K*eps_int).
  NORM:   K cycles, walk i=0..K-1, y_buf[i] = (x_buf[i] * gamma[i] * rsqrt_val) >> shift.
  DONE:   1 cycle, expose y_packed and done.

Resources: 1 squarer, 1 sum_sq accumulator, 1 rsqrt LUT, 1 multiplier for
normalisation, K-element activation buffer, K-element output register file,
K-element gamma ROM. The rsqrt LUT is emitted as a separate RawSubmodule so
multiple RMSNorms with the same K and bit widths share one ROM.

Numerical model:
  x[i]:          int signed, ABITS bits, Q-format up to caller.
  gamma_int[i]:  int signed, GBITS bits.
  eps:           float; baked in as eps_int = round(eps * EPS_SCALE).
  sum_sq:        unsigned accumulator, SUM_SQ_BITS = 2*ABITS + ceil(log2(K)).
  rsqrt_val:     Q1.RSQRT_FRAC_BITS unsigned.
  product = x[i] * gamma[i] * rsqrt_val (signed * signed * unsigned).
  y[i]   = sat( product >>> output_shift ).

Generalises across LLaMA / Qwen / Mistral / SmolLM2 (every one of these
uses RMSNorm with the same gamma * x / sqrt(mean(x^2) + eps) structure).
"""
from __future__ import annotations

import math
from textwrap import dedent

from ..core import Gate, RawSubmodule
from .rsqrt import rsqrt_block, rsqrt_module_name


def rms_norm_module_name(
    K: int, abits: int, gbits: int, obits: int,
) -> str:
    return f"rms_norm_K{K}_a{abits}_g{gbits}_o{obits}"


def _signed_mask(value: int, width: int) -> int:
    return value & ((1 << width) - 1)


def rms_norm_block(
    *,
    K: int,
    gamma_int: list[int],
    gamma_bits: int = 16,
    abits: int = 8,
    obits: int = 8,
    eps: float = 1e-5,
    eps_q: int = 16,                 # eps_int = round(eps * 2**eps_q)
    rsqrt_in_bits: int | None = None,
    rsqrt_out_bits: int = 16,
    rsqrt_out_frac_bits: int = 14,
    output_shift: int = 14,
    module_suffix: str = "",
) -> tuple[RawSubmodule, RawSubmodule]:
    """Build the RMSNorm submodule + its rsqrt LUT companion.

    Returns ``(rms_norm_submodule, rsqrt_submodule)``. The caller must add
    both to ``graph.submodules`` (the hierarchical emit dedups by name so
    multiple RMSNorms sharing a shape only emit one rsqrt LUT).

    K, abits, obits: as in the docstring.
    gamma_int:   per-element gamma as signed integers in ``gamma_bits``.
    eps_q:       fractional bits of eps (eps_int = round(eps * 2**eps_q)).
                 Make sure SUM_SQ_BITS leaves room for the eps adjustment.
    output_shift: arithmetic right shift after (x * gamma * rsqrt_val).
                 Choose so that typical outputs land in [-2**(obits-1), 2**(obits-1)).
    """
    if K < 1:
        raise ValueError("K must be >= 1")
    if len(gamma_int) != K:
        raise ValueError(f"gamma_int length {len(gamma_int)} != K={K}")

    sum_sq_bits = 2 * abits + max(1, K.bit_length())
    if rsqrt_in_bits is None:
        rsqrt_in_bits = sum_sq_bits + 4   # headroom for eps addition

    counter_bits = max(1, (K - 1).bit_length() + 1)

    eps_int = round(eps * (1 << eps_q))
    K_eps_int = K * eps_int   # what we add to sum_sq before rsqrt

    base_name = rms_norm_module_name(K, abits, gamma_bits, obits)
    name = base_name + (f"_{module_suffix}" if module_suffix else "")

    rsqrt = rsqrt_block(
        in_bits=rsqrt_in_bits,
        out_bits=rsqrt_out_bits,
        out_frac_bits=rsqrt_out_frac_bits,
    )
    rsqrt_name = rsqrt.top

    # gamma ROM init lines
    gamma_init = "\n".join(
        f"    gamma_rom[{i}] = {gamma_bits}'h"
        f"{_signed_mask(gamma_int[i], gamma_bits):x};"
        for i in range(K)
    )

    out_lo = -(1 << (obits - 1))
    out_hi = (1 << (obits - 1)) - 1
    sat_bits = abits + gamma_bits + rsqrt_out_bits

    text = dedent(f"""\
        // Generated by safetensors2verilog.blocks.rms_norm.
        // RMSNorm: y = (x * gamma) * rsqrt(sum(x^2) + K*eps)
        //   K = {K}, abits = {abits}, gbits = {gamma_bits}, obits = {obits}
        //   eps = {eps:.3e} -> eps_int = {eps_int}, K*eps_int = {K_eps_int}
        //   sum_sq_bits = {sum_sq_bits}, rsqrt_in_bits = {rsqrt_in_bits}
        //   output_shift = {output_shift}
        //   latency = 2K + 3 = {2*K + 3} cycles per token

        `default_nettype none

        module {name} (
          input  wire                              clk,
          input  wire                              rst,
          input  wire                              start,
          input  wire signed [{K*abits-1}:0]        x_packed,
          output wire                              done,
          output wire signed [{K*obits-1}:0]        y_packed
        );

          // ---- State machine -------------------------------------------------
          localparam [2:0] STATE_IDLE   = 3'd0;
          localparam [2:0] STATE_ACCUM  = 3'd1;
          localparam [2:0] STATE_LOOKUP = 3'd2;
          localparam [2:0] STATE_NORM   = 3'd3;
          localparam [2:0] STATE_DONE   = 3'd4;

          reg [2:0] state;
          reg [{counter_bits-1}:0] counter;
          wire counter_at_max = (counter == {K-1});

          always @(posedge clk or posedge rst) begin
            if (rst) begin
              state   <= STATE_IDLE;
              counter <= 0;
            end else case (state)
              STATE_IDLE: begin
                counter <= 0;
                if (start) state <= STATE_ACCUM;
              end
              STATE_ACCUM: begin
                if (counter_at_max) begin
                  state   <= STATE_LOOKUP;
                  counter <= 0;
                end else begin
                  counter <= counter + 1'b1;
                end
              end
              STATE_LOOKUP: begin
                state   <= STATE_NORM;
                counter <= 0;
              end
              STATE_NORM: begin
                if (counter_at_max) begin
                  state   <= STATE_DONE;
                  counter <= 0;
                end else begin
                  counter <= counter + 1'b1;
                end
              end
              STATE_DONE:  state <= STATE_IDLE;
              default:     state <= STATE_IDLE;
            endcase
          end

          assign done = (state == STATE_DONE);

          // ---- Activation buffer (latched on start in IDLE) ----------------
          reg signed [{abits-1}:0] x_buf [0:{K-1}];
          integer i;
          always @(posedge clk) begin
            if (state == STATE_IDLE && start) begin
              for (i = 0; i < {K}; i = i + 1) begin
                x_buf[i] <= $signed(x_packed[i*{abits} +: {abits}]);
              end
            end
          end

          wire signed [{abits-1}:0] x_now = x_buf[counter];

          // ---- Sum of squares accumulator ---------------------------------
          reg [{sum_sq_bits-1}:0] sum_sq;
          wire signed [{2*abits-1}:0] sq = x_now * x_now;
          always @(posedge clk or posedge rst) begin
            if (rst)
              sum_sq <= 0;
            else if (state == STATE_IDLE && start)
              sum_sq <= 0;
            else if (state == STATE_ACCUM)
              sum_sq <= sum_sq + sq[{2*abits-1}:0];
          end

          // ---- rsqrt instance --------------------------------------------
          // sum_sq_eps = sum_sq + K*eps_int  (combinational)
          wire [{rsqrt_in_bits-1}:0] sum_sq_eps =
            sum_sq + {rsqrt_in_bits}'h{K_eps_int:x};

          wire [{rsqrt_out_bits-1}:0] rsqrt_val_comb;
          {rsqrt_name} rsqrt_inst (
            .x(sum_sq_eps),
            .y(rsqrt_val_comb)
          );

          // Latch rsqrt_val on the LOOKUP cycle so the NORM stage can
          // use it stably across K cycles (rsqrt_lut is combinational).
          reg [{rsqrt_out_bits-1}:0] rsqrt_val;
          always @(posedge clk) begin
            if (state == STATE_LOOKUP) rsqrt_val <= rsqrt_val_comb;
          end

          // ---- Gamma ROM --------------------------------------------------
          (* ram_style = "block" *)
          reg signed [{gamma_bits-1}:0] gamma_rom [0:{K-1}];
          initial begin
        {gamma_init}
          end
          wire signed [{gamma_bits-1}:0] gamma_now = gamma_rom[counter];

          // ---- Normalisation: y[i] = sat( (x[i] * gamma[i] * rsqrt_val) >>> shift ) -
          // x_now: signed abits.
          // gamma_now: signed gbits.
          // rsqrt_val: unsigned rsqrt_out_bits, treated as positive scale.
          // Product width: abits + gbits + rsqrt_out_bits, signed.
          wire signed [{abits + gamma_bits - 1}:0] xg = x_now * gamma_now;
          wire signed [{abits + gamma_bits + rsqrt_out_bits - 1}:0] xgr =
            xg * $signed({{1'b0, rsqrt_val}});
          wire signed [{abits + gamma_bits + rsqrt_out_bits - 1}:0] shifted =
            xgr >>> {output_shift};
          wire signed [{obits-1}:0] y_sat =
            (shifted > {out_hi}) ? {obits}'sd{out_hi}
          : (shifted < ({out_lo})) ? -{obits}'sd{abs(out_lo)}
          : shifted[{obits-1}:0];

          // ---- Output register file -------------------------------------
          reg signed [{obits-1}:0] y_buf [0:{K-1}];
          always @(posedge clk) begin
            if (state == STATE_NORM) y_buf[counter] <= y_sat;
          end

          genvar j;
          generate
            for (j = 0; j < {K}; j = j + 1) begin: pack
              assign y_packed[j*{obits} +: {obits}] = y_buf[j];
            end
          endgenerate

        endmodule

        `default_nettype wire
        """)

    return RawSubmodule(top=name, text=text), rsqrt


def rms_norm_invoke(
    *,
    instance_name: str,
    parent_x_packed: str,
    parent_clk: str,
    parent_rst: str,
    parent_start: str,
    K: int,
    gamma_int: list[int],
    gamma_bits: int = 16,
    abits: int = 8,
    obits: int = 8,
    eps: float = 1e-5,
    eps_q: int = 16,
    rsqrt_in_bits: int | None = None,
    rsqrt_out_bits: int = 16,
    rsqrt_out_frac_bits: int = 14,
    output_shift: int = 14,
    y_signal: str | None = None,
    done_signal: str | None = None,
) -> tuple[list[RawSubmodule], list[Gate]]:
    """Returns ([rms_norm submodule, rsqrt submodule], [gates])."""
    rms, rsqrt = rms_norm_block(
        K=K, gamma_int=gamma_int, gamma_bits=gamma_bits,
        abits=abits, obits=obits, eps=eps, eps_q=eps_q,
        rsqrt_in_bits=rsqrt_in_bits,
        rsqrt_out_bits=rsqrt_out_bits,
        rsqrt_out_frac_bits=rsqrt_out_frac_bits,
        output_shift=output_shift,
    )
    if y_signal is None:
        y_signal = f"{instance_name}_y_packed"
    if done_signal is None:
        done_signal = f"{instance_name}_done"

    gates = [
        Gate(name=done_signal, kind="extern_wire", output_width=1,
             output_signed=False),
        Gate(
            name=y_signal,
            kind="instance",
            inputs=[parent_clk, parent_rst, parent_start, parent_x_packed],
            attrs={
                "module_name": rms.top,
                "instance_name": instance_name,
                "input_ports": ["clk", "rst", "start", "x_packed"],
                "output_port": "y_packed",
                "extra_output_ports": [("done", done_signal)],
            },
            output_width=K * obits,
            output_signed=True,
        ),
    ]
    return [rms, rsqrt], gates
