"""LUT-based fixed-point reciprocal square root.

Used inside RMSNorm. The standard FPGA implementation is:

  1. Find the leading-1 position of the input (count leading zeros).
  2. Normalise: shift the input so its MSB is in a known position.
  3. Look up rsqrt of the normalised value in a small LUT (256 entries).
  4. Apply a power-of-2 scaling derived from the leading-zero count.
  5. (Optional) one Newton iteration to refine.

This implementation does steps 1-4 (no Newton refinement yet — accuracy
is roughly 8-9 bits of mantissa, plenty for inference). Newton refinement
is left as a follow-up.

Module signature is generic — caller chooses input width up to 32 bits.
The block is combinational once the input is stable; if the upstream
sum-of-squares is registered, this stage adds only its own propagation
delay. To pipeline, register the LUT output explicitly.

Output Q-format: Q1.``out_frac_bits`` unsigned, where the LSB represents
``2**-out_frac_bits``. For typical RMSNorm use, ``out_frac_bits=16`` covers
rsqrt outputs in ``[2**-15, 1)`` which is the practical inference range
(rsqrt of small values in normalised activations).

For inputs outside the LUT-supported range the output saturates: very
small inputs yield the maximum representable rsqrt; very large inputs
yield a near-zero result.
"""
from __future__ import annotations

import math
from textwrap import dedent

from ..core import Gate, RawSubmodule


def rsqrt_module_name(in_bits: int, out_bits: int) -> str:
    return f"rsqrt_lut_in{in_bits}_out{out_bits}"


def _count_leading_zeros_verilog(in_bits: int) -> str:
    """Generate a casez statement that returns CLZ for an in_bits-wide signal."""
    lines = [f"  function automatic [{(in_bits-1).bit_length() - 1}:0] clz;"]
    lines.append(f"    input [{in_bits-1}:0] v;")
    lines.append("    casez (v)")
    for k in range(in_bits):
        # Leading bit is at position in_bits - 1 - k
        lead_pos = in_bits - 1 - k
        # Pattern: k zeros then 1 then anything
        zeros = "0" * k
        ones = "1"
        rest = "?" * lead_pos
        lines.append(f"      {in_bits}'b{zeros}{ones}{rest}: clz = {k};")
    lines.append(f"      default: clz = {in_bits};")
    lines.append("    endcase")
    lines.append("  endfunction")
    return "\n".join(lines)


def rsqrt_block(
    *,
    in_bits: int = 32,
    out_bits: int = 16,
    out_frac_bits: int = 14,
    lut_idx_bits: int = 8,
    module_suffix: str = "",
) -> RawSubmodule:
    """Combinational rsqrt approximator.

    in_bits:        unsigned input width (typical: 24-32 for sum-of-squares)
    out_bits:       output width (unsigned). Should be >= out_frac_bits + 1.
    out_frac_bits:  fractional bits of the output Q-format. The output
                    represents ``raw / 2**out_frac_bits``.
    lut_idx_bits:   LUT size = 2**lut_idx_bits entries. 8 = 256 entries
                    (plenty for ~9 bits of mantissa). 10 for higher accuracy.

    Algorithm:
      Let v = input. Find msb position p such that v in [2**p, 2**(p+1)).
      Decompose v = 2**p * (1 + frac), frac in [0, 1).
      rsqrt(v) = 2**(-p/2) * rsqrt(1 + frac).
      LUT[idx] = round(rsqrt(1 + idx/2**lut_idx_bits) * 2**out_frac_bits).
      The 2**(-p/2) scaling is integer-shift for even p, and multiply by
      sqrt(1/2) ~ 0.707 for odd p. We bake the sqrt(1/2) factor into a
      second LUT-equivalent constant.
    """
    if in_bits < 4 or out_bits < 4:
        raise ValueError("bit widths too small for rsqrt block")
    n_entries = 1 << lut_idx_bits
    out_max = (1 << out_bits) - 1

    base = rsqrt_module_name(in_bits, out_bits)
    name = base + (f"_{module_suffix}" if module_suffix else "")

    # LUT contents: rsqrt(1 + i / 2**lut_idx_bits) in Q1.out_frac_bits unsigned.
    lut: list[int] = []
    for i in range(n_entries):
        frac = i / n_entries
        v = 1.0 + frac
        rs = 1.0 / math.sqrt(v)
        out_int = max(0, min(out_max, round(rs * (1 << out_frac_bits))))
        lut.append(out_int)
    init_lines = "\n".join(
        f"    rom[{i}] = {out_bits}'h{lut[i]:x};" for i in range(n_entries)
    )

    sqrt_half_q = round(math.sqrt(0.5) * (1 << out_frac_bits))   # ~ 0.7071 in Q
    sqrt_half_lit = f"{out_bits + out_frac_bits}'h{sqrt_half_q:x}"

    clz_func = _count_leading_zeros_verilog(in_bits)
    p_bits = max(1, (in_bits).bit_length())
    extract_bits = lut_idx_bits + 1   # leading 1 + lut_idx_bits of fraction

    text = dedent(f"""\
        // Generated by safetensors2verilog.blocks.rsqrt.
        // LUT-based reciprocal square root.
        // Input: unsigned {in_bits}-bit. Output: Q1.{out_frac_bits} unsigned ({out_bits}-bit).
        // Algorithm: leading-zero normalise -> {n_entries}-entry LUT -> half-power scale.

        `default_nettype none

        module {name} (
          input  wire [{in_bits-1}:0] x,
          output wire [{out_bits-1}:0] y
        );

        {clz_func}

          (* ram_style = "block" *)
          reg [{out_bits-1}:0] rom [0:{n_entries-1}];
          initial begin
        {init_lines}
          end

          // p = position of leading 1 in x; for x = 0 we set p = 0 and y = max.
          wire [{p_bits-1}:0] lz = clz(x);
          wire is_zero = (x == 0);
          wire [{p_bits-1}:0] p = is_zero ? 0 : ({in_bits} - 1 - lz);

          // Normalise: shift x left so the MSB sits at bit (in_bits-1).
          wire [{in_bits-1}:0] x_norm = is_zero ? 0 : (x << lz);
          // Take next lut_idx_bits below the leading 1 as LUT index.
          wire [{lut_idx_bits-1}:0] idx =
            x_norm[{in_bits - 2}:{in_bits - 1 - lut_idx_bits}];

          wire [{out_bits-1}:0] lut_val = rom[idx];

          // Power-of-2 rescale: rsqrt(2^p * (1 + frac)) = 2^(-p/2) * lut_val.
          // For even p: shift right by p/2.  For odd p: shift right by (p+1)/2 then * sqrt(2).
          // Equivalent: shift right by p/2 then multiply by sqrt(1/2) when p odd.
          wire p_odd = p[0];
          wire [{p_bits-1}:0] half_p = p >> 1;

          // shift right by half_p, then conditionally multiply by sqrt_half_q.
          wire [{out_bits-1}:0] shifted = lut_val >> half_p;
          wire [{out_bits + out_frac_bits - 1}:0] product = shifted * {sqrt_half_lit};
          wire [{out_bits-1}:0] scaled = product[{out_bits + out_frac_bits - 1}:{out_frac_bits}];

          assign y = is_zero ? {out_bits}'h{out_max:x}
                   : (p_odd ? scaled : shifted);
        endmodule

        `default_nettype wire
        """)
    return RawSubmodule(top=name, text=text)
