"""LUT-based fixed-point sigmoid.

Sigmoid saturates outside roughly [-8, 8], so the LUT clamps inputs to a
configurable range and indexes a small ROM. Output is unsigned ``out_bits``
with format Q0.``out_bits`` (the value ``raw / 2**out_bits``).

Default: 8-bit signed input clamped to [-8, 7.9375] (Q4.4), 256-entry LUT
of 8-bit unsigned outputs (Q0.8). 256 bytes per instance, combinational.

For SmolLM2 / Qwen / Mistral the gate-projection pre-activation rarely
escapes ±10 in inference; the clamp is conservative.

Generalises across LLaMA-family and any model whose `hidden_act = silu`,
`gelu`, etc. (for GELU we'd use a separate LUT with the same harness).
"""
from __future__ import annotations

import math
from textwrap import dedent

from ..core import Gate, RawSubmodule


def sigmoid_module_name(in_bits: int, out_bits: int) -> str:
    return f"sigmoid_lut_in{in_bits}_out{out_bits}"


def sigmoid_block(
    *,
    in_bits: int = 8,
    out_bits: int = 8,
    in_q_frac_bits: int = 4,
    in_clamp: tuple[float, float] = (-8.0, 8.0),
    module_suffix: str = "",
) -> RawSubmodule:
    """Combinational sigmoid LUT.

    in_bits:        signed input width
    out_bits:       unsigned output width (Q0.out_bits)
    in_q_frac_bits: number of fractional bits in the input (the input
                    represents x = raw / 2**in_q_frac_bits)
    in_clamp:       clamp (lo, hi) applied to the dequantised input before
                    LUT lookup. Values outside this range pin to the LUT
                    extremes (sigmoid is essentially 0 / 1 there).
    """
    if in_bits < 2 or out_bits < 2:
        raise ValueError("bit widths too small")
    n_entries = 1 << in_bits
    in_lo_int = -(1 << (in_bits - 1))
    in_hi_int = (1 << (in_bits - 1)) - 1
    out_max = (1 << out_bits) - 1

    base = sigmoid_module_name(in_bits, out_bits)
    name = base + (f"_{module_suffix}" if module_suffix else "")

    # Build the LUT contents indexed by the unsigned representation of
    # the signed input (i.e. two's-complement bit pattern).
    lut: list[int] = []
    for raw in range(n_entries):
        # decode signed
        if raw & (1 << (in_bits - 1)):
            sint = raw - (1 << in_bits)
        else:
            sint = raw
        x = sint / (1 << in_q_frac_bits)
        x = max(in_clamp[0], min(in_clamp[1], x))
        s = 1.0 / (1.0 + math.exp(-x))
        out_int = max(0, min(out_max, round(s * (1 << out_bits))))
        # cap at out_max because round(1.0 * 2**out_bits) = 2**out_bits which
        # overflows out_bits unsigned.
        lut.append(out_int)

    init_lines = "\n".join(
        f"    rom[{i}] = {out_bits}'h{lut[i]:x};" for i in range(n_entries)
    )
    text = dedent(f"""\
        // Generated by safetensors2verilog.blocks.sigmoid.
        // LUT-based sigmoid. in_bits={in_bits} (signed Q{in_bits-in_q_frac_bits-1}.{in_q_frac_bits}),
        // out_bits={out_bits} (unsigned Q0.{out_bits}).
        // ROM size: {n_entries} entries x {out_bits} bits = {n_entries * out_bits // 8} bytes.

        `default_nettype none

        module {name} (
          input  wire signed [{in_bits-1}:0] x,
          output wire        [{out_bits-1}:0] y
        );
          (* ram_style = "block" *)
          reg [{out_bits-1}:0] rom [0:{n_entries-1}];
          initial begin
        {init_lines}
          end
          // Index by unsigned bit pattern of x; sigmoid LUT is precomputed
          // in two's-complement order so this is a direct lookup.
          assign y = rom[x[{in_bits-1}:0]];
        endmodule

        `default_nettype wire
        """)

    return RawSubmodule(top=name, text=text)


def sigmoid_invoke(
    *,
    instance_name: str,
    parent_x_signal: str,
    in_bits: int = 8,
    out_bits: int = 8,
    in_q_frac_bits: int = 4,
    in_clamp: tuple[float, float] = (-8.0, 8.0),
    y_signal: str | None = None,
) -> tuple[RawSubmodule, list[Gate]]:
    """Returns (submodule, [instance gate])."""
    sub = sigmoid_block(
        in_bits=in_bits, out_bits=out_bits,
        in_q_frac_bits=in_q_frac_bits, in_clamp=in_clamp,
    )
    if y_signal is None:
        y_signal = f"{instance_name}_y"
    gates = [
        Gate(
            name=y_signal,
            kind="instance",
            inputs=[parent_x_signal],
            attrs={
                "module_name": sub.top,
                "instance_name": instance_name,
                "input_ports": ["x"],
                "output_port": "y",
            },
            output_width=out_bits,
            output_signed=False,
        ),
    ]
    return sub, gates
