"""SiLU (Swish) activation: y = x * sigmoid(x).

Sequential, K-cycle block. Reuses one sigmoid LUT and one multiplier across
all K elements. Returned as an in-out packed-bus block matching the rest of
the LLM stack's interface convention.

For SmolLM2, Qwen, Mistral and any model with ``hidden_act = silu``.
"""
from __future__ import annotations

from textwrap import dedent

from ..core import Gate, RawSubmodule
from .sigmoid import sigmoid_block, sigmoid_module_name


def silu_module_name(K: int, abits: int, obits: int) -> str:
    return f"silu_seq_K{K}_a{abits}_o{obits}"


def silu_block(
    *,
    K: int,
    abits: int = 8,
    obits: int = 8,
    sigmoid_in_q_frac_bits: int = 4,
    sigmoid_out_bits: int = 8,
    output_shift: int = 8,
    module_suffix: str = "",
) -> tuple[RawSubmodule, RawSubmodule]:
    """Build (silu submodule, sigmoid LUT submodule).

    Sigmoid output is unsigned Q0.sigmoid_out_bits. After multiplying by
    x (signed abits), the product is signed (abits + sigmoid_out_bits).
    Right-shift by ``output_shift`` to match the desired output Q-format.
    """
    sig = sigmoid_block(
        in_bits=abits, out_bits=sigmoid_out_bits,
        in_q_frac_bits=sigmoid_in_q_frac_bits,
    )
    counter_bits = max(1, (K - 1).bit_length() + 1)
    base = silu_module_name(K, abits, obits)
    name = base + (f"_{module_suffix}" if module_suffix else "")

    out_lo = -(1 << (obits - 1))
    out_hi = (1 << (obits - 1)) - 1

    text = dedent(f"""\
        // Generated by safetensors2verilog.blocks.silu.
        // Sequential SiLU: y = x * sigmoid(x). K = {K}, abits = {abits}, obits = {obits}.
        // latency = K + 2 cycles per token.

        `default_nettype none

        module {name} (
          input  wire                            clk,
          input  wire                            rst,
          input  wire                            start,
          input  wire signed [{K*abits-1}:0]      x_packed,
          output wire                            done,
          output wire signed [{K*obits-1}:0]      y_packed
        );

          localparam [1:0] STATE_IDLE    = 2'd0;
          localparam [1:0] STATE_COMPUTE = 2'd1;
          localparam [1:0] STATE_DONE    = 2'd2;

          reg [1:0] state;
          reg [{counter_bits-1}:0] counter;
          wire counter_at_max = (counter == {K-1});

          always @(posedge clk or posedge rst) begin
            if (rst) begin state <= STATE_IDLE; counter <= 0; end
            else case (state)
              STATE_IDLE: begin
                counter <= 0;
                if (start) state <= STATE_COMPUTE;
              end
              STATE_COMPUTE:
                if (counter_at_max) begin
                  state <= STATE_DONE; counter <= 0;
                end else counter <= counter + 1'b1;
              STATE_DONE: state <= STATE_IDLE;
              default:    state <= STATE_IDLE;
            endcase
          end

          assign done = (state == STATE_DONE);

          reg signed [{abits-1}:0] x_buf [0:{K-1}];
          integer i;
          always @(posedge clk) begin
            if (state == STATE_IDLE && start)
              for (i = 0; i < {K}; i = i + 1)
                x_buf[i] <= $signed(x_packed[i*{abits} +: {abits}]);
          end

          wire signed [{abits-1}:0] x_now = x_buf[counter];

          wire [{sigmoid_out_bits-1}:0] sig_y;
          {sig.top} sig_inst (.x(x_now), .y(sig_y));

          // y = (x * sig) >>> shift, saturated.
          wire signed [{abits + sigmoid_out_bits - 1}:0] prod =
            x_now * $signed({{1'b0, sig_y}});
          wire signed [{abits + sigmoid_out_bits - 1}:0] shifted =
            prod >>> {output_shift};
          wire signed [{obits-1}:0] y_sat =
            (shifted > {out_hi}) ? {obits}'sd{out_hi}
          : (shifted < ({out_lo})) ? -{obits}'sd{abs(out_lo)}
          : shifted[{obits-1}:0];

          reg signed [{obits-1}:0] y_buf [0:{K-1}];
          always @(posedge clk) begin
            if (state == STATE_COMPUTE) y_buf[counter] <= y_sat;
          end

          genvar j;
          generate
            for (j = 0; j < {K}; j = j + 1) begin: pack
              assign y_packed[j*{obits} +: {obits}] = y_buf[j];
            end
          endgenerate

        endmodule

        `default_nettype wire
        """)

    return RawSubmodule(top=name, text=text), sig


def silu_invoke(
    *,
    instance_name: str,
    parent_x_packed: str,
    parent_clk: str, parent_rst: str, parent_start: str,
    K: int, abits: int = 8, obits: int = 8,
    sigmoid_in_q_frac_bits: int = 4,
    sigmoid_out_bits: int = 8,
    output_shift: int = 8,
    y_signal: str | None = None,
    done_signal: str | None = None,
) -> tuple[list[RawSubmodule], list[Gate]]:
    silu, sig = silu_block(
        K=K, abits=abits, obits=obits,
        sigmoid_in_q_frac_bits=sigmoid_in_q_frac_bits,
        sigmoid_out_bits=sigmoid_out_bits,
        output_shift=output_shift,
    )
    if y_signal is None: y_signal = f"{instance_name}_y_packed"
    if done_signal is None: done_signal = f"{instance_name}_done"
    gates = [
        Gate(name=done_signal, kind="extern_wire", output_width=1),
        Gate(
            name=y_signal, kind="instance",
            inputs=[parent_clk, parent_rst, parent_start, parent_x_packed],
            attrs={
                "module_name": silu.top, "instance_name": instance_name,
                "input_ports": ["clk", "rst", "start", "x_packed"],
                "output_port": "y_packed",
                "extra_output_ports": [("done", done_signal)],
            },
            output_width=K * obits, output_signed=True,
        ),
    ]
    return [silu, sig], gates
