"""Numerically-stable softmax: y[i] = exp(x[i] - max(x)) / sum_j exp(x[j] - max(x)).

Three-pass sequential block (latency 3K + ~5 cycles):

  PASS_MAX: K cycles, find max(x[0..K-1]).
  PASS_EXP: K cycles, exp_buf[i] = exp_lut(x[i] - max), accumulate sum_exp.
  PASS_DIV: K cycles, y[i] = exp_buf[i] * invert(sum_exp), as a multiply by
            a precomputed reciprocal (sum_exp -> 1/sum_exp via a small
            inversion LUT).

Inputs are signed; outputs are unsigned Q0.``out_bits`` representing
probabilities in [0, 1).

For attention's masked softmax we accept a separate ``mask_packed`` of
K bits where ``mask[i]==1`` zeroes the corresponding probability (used
to implement causal attention). When mask is the constant 1 the block
reduces to plain softmax.
"""
from __future__ import annotations

import math
from textwrap import dedent

from ..core import Gate, RawSubmodule
from .exp import exp_block


def softmax_module_name(K: int, abits: int, obits: int) -> str:
    return f"softmax_K{K}_a{abits}_o{obits}"


def _build_recip_lut(
    n_entries: int, max_in_value: int, out_frac_bits: int, out_bits: int,
) -> list[int]:
    """LUT[idx] = round((1 / (idx_value)) * 2**out_frac_bits) for idx >= 1.

    Indexed by sum_exp's high bits after leading-zero alignment is the
    proper FPGA approach; here we use a direct LUT for simplicity.
    Caller picks ``max_in_value`` such that sum_exp values fit within the
    LUT's address range (sum_exp / scale_factor = idx).
    """
    out_max = (1 << out_bits) - 1
    lut: list[int] = [0]   # idx=0: avoid div by zero, output 0 (won't be used)
    for idx in range(1, n_entries):
        v = 1.0 / idx
        out = max(0, min(out_max, round(v * (1 << out_frac_bits))))
        lut.append(out)
    return lut


def softmax_block(
    *,
    K: int,
    abits: int = 8,
    obits: int = 8,
    exp_in_bits: int = 8,
    exp_out_bits: int = 12,
    exp_in_q_frac_bits: int = 4,
    exp_in_clamp: tuple[float, float] = (-16.0, 0.0),
    recip_lut_bits: int = 12,
    recip_out_frac_bits: int = 16,
    output_shift: int = 8,
    module_suffix: str = "",
) -> tuple[RawSubmodule, RawSubmodule]:
    """Build (softmax submodule, exp LUT submodule).

    K, abits, obits as elsewhere. The exp LUT is shared across softmax
    invocations of the same shape via the hierarchical-emit dedup.

    Note: the recip LUT is baked inline into the softmax module (small
    enough; recip_lut_bits=12 -> 4096 entries ~ 8 KB).
    """
    if K < 2:
        raise ValueError("K must be >= 2 for softmax")
    counter_bits = max(1, (K - 1).bit_length() + 1)
    sum_exp_bits = exp_out_bits + max(1, K.bit_length())

    base = softmax_module_name(K, abits, obits)
    name = base + (f"_{module_suffix}" if module_suffix else "")

    exp = exp_block(
        in_bits=exp_in_bits, out_bits=exp_out_bits,
        in_q_frac_bits=exp_in_q_frac_bits, in_clamp=exp_in_clamp,
    )

    n_recip = 1 << recip_lut_bits
    recip_lut = _build_recip_lut(
        n_recip, max_in_value=n_recip - 1,
        out_frac_bits=recip_out_frac_bits, out_bits=24,
    )
    recip_init = "\n".join(
        f"    recip_rom[{i}] = 24'h{recip_lut[i]:x};" for i in range(n_recip)
    )

    out_max = (1 << obits) - 1

    text = dedent(f"""\
        // Generated by safetensors2verilog.blocks.softmax.
        // Numerically-stable softmax. K = {K}, abits = {abits}, obits = {obits}.
        // 3-pass sequential, latency = 3K + 5 = {3*K + 5} cycles.

        `default_nettype none

        module {name} (
          input  wire                            clk,
          input  wire                            rst,
          input  wire                            start,
          input  wire signed [{K*abits-1}:0]      x_packed,
          input  wire        [{K-1}:0]            mask,
          output wire                            done,
          output wire        [{K*obits-1}:0]      y_packed
        );

          localparam [2:0] STATE_IDLE     = 3'd0;
          localparam [2:0] STATE_PASS_MAX = 3'd1;
          localparam [2:0] STATE_PASS_EXP = 3'd2;
          localparam [2:0] STATE_INVERT   = 3'd3;
          localparam [2:0] STATE_PASS_DIV = 3'd4;
          localparam [2:0] STATE_DONE     = 3'd5;

          reg [2:0] state;
          reg [{counter_bits-1}:0] counter;
          wire counter_at_max = (counter == {K-1});

          always @(posedge clk or posedge rst) begin
            if (rst) begin state <= STATE_IDLE; counter <= 0; end
            else case (state)
              STATE_IDLE:     if (start) begin state <= STATE_PASS_MAX; counter <= 0; end
                              else counter <= 0;
              STATE_PASS_MAX: if (counter_at_max) begin state <= STATE_PASS_EXP; counter <= 0; end
                              else counter <= counter + 1'b1;
              STATE_PASS_EXP: if (counter_at_max) begin state <= STATE_INVERT; counter <= 0; end
                              else counter <= counter + 1'b1;
              STATE_INVERT:   begin state <= STATE_PASS_DIV; counter <= 0; end
              STATE_PASS_DIV: if (counter_at_max) begin state <= STATE_DONE; counter <= 0; end
                              else counter <= counter + 1'b1;
              STATE_DONE:     state <= STATE_IDLE;
              default:        state <= STATE_IDLE;
            endcase
          end

          assign done = (state == STATE_DONE);

          // ---- Activation buffer + mask buffer --------------------------
          reg signed [{abits-1}:0] x_buf [0:{K-1}];
          reg [{K-1}:0]            mask_buf;
          integer i;
          // Blocking assignment to x_buf array elements: verilator rejects
          // NBA to array elements inside for-loops. Single writer, same
          // semantics here.
          always @(posedge clk) begin
            if (state == STATE_IDLE && start) begin
              for (i = 0; i < {K}; i = i + 1)
                x_buf[i] = $signed(x_packed[i*{abits} +: {abits}]);
              mask_buf <= mask;
            end
          end

          wire signed [{abits-1}:0] x_now = x_buf[counter];
          wire mask_now = mask_buf[counter];

          // ---- PASS_MAX: track running max (treats masked entries as -inf) ---
          reg signed [{abits-1}:0] cur_max;
          always @(posedge clk or posedge rst) begin
            if (rst)
              cur_max <= -{abits}'sd{(1 << (abits - 1)) - 1};
            else if (state == STATE_IDLE && start)
              cur_max <= -{abits}'sd{(1 << (abits - 1)) - 1};
            else if (state == STATE_PASS_MAX && mask_now && (x_now > cur_max))
              cur_max <= x_now;
          end

          // ---- PASS_EXP: x_diff = x[i] - cur_max (always <= 0). Lookup exp. -
          wire signed [{abits}:0] x_diff_wide = x_now - cur_max;
          wire signed [{exp_in_bits-1}:0] x_diff =
            (x_diff_wide < -{exp_in_bits}'sd{(1 << (exp_in_bits-1)) - 1})
              ? -{exp_in_bits}'sd{(1 << (exp_in_bits-1)) - 1}
            : x_diff_wide[{exp_in_bits-1}:0];

          wire [{exp_out_bits-1}:0] exp_y_raw;
          {exp.top} exp_inst (.x(x_diff), .y(exp_y_raw));
          wire [{exp_out_bits-1}:0] exp_y = mask_now ? exp_y_raw : 0;

          reg [{exp_out_bits-1}:0] exp_buf [0:{K-1}];
          reg [{sum_exp_bits-1}:0] sum_exp;
          always @(posedge clk or posedge rst) begin
            if (rst)
              sum_exp <= 0;
            else if (state == STATE_IDLE && start)
              sum_exp <= 0;
            else if (state == STATE_PASS_EXP) begin
              exp_buf[counter] <= exp_y;
              sum_exp <= sum_exp + exp_y;
            end
          end

          // ---- INVERT: recip_val = 1 / sum_exp via LUT ------------------
          (* ram_style = "block" *)
          reg [23:0] recip_rom [0:{n_recip-1}];
          initial begin
        {recip_init}
          end
          // sum_exp may exceed recip_lut_bits — clamp the index.
          wire [{recip_lut_bits-1}:0] recip_idx =
            (sum_exp >= {n_recip}) ? {recip_lut_bits}'h{n_recip - 1:x}
                                   : sum_exp[{recip_lut_bits-1}:0];
          reg [23:0] recip_val;
          always @(posedge clk) begin
            if (state == STATE_INVERT) recip_val <= recip_rom[recip_idx];
          end

          // ---- PASS_DIV: y[i] = exp_buf[i] * recip_val >>> output_shift -
          wire [{exp_out_bits-1}:0] eb_now = exp_buf[counter];
          wire [{exp_out_bits + 24 - 1}:0] divprod = eb_now * recip_val;
          wire [{exp_out_bits + 24 - 1}:0] divshift = divprod >>> {output_shift};
          wire [{obits-1}:0] y_sat =
            (divshift > {out_max}) ? {obits}'h{out_max:x}
                                  : divshift[{obits-1}:0];

          reg [{obits-1}:0] y_buf [0:{K-1}];
          always @(posedge clk) begin
            if (state == STATE_PASS_DIV) y_buf[counter] <= y_sat;
          end

          genvar j;
          generate
            for (j = 0; j < {K}; j = j + 1) begin: pack
              assign y_packed[j*{obits} +: {obits}] = y_buf[j];
            end
          endgenerate

        endmodule

        `default_nettype wire
        """)

    return RawSubmodule(top=name, text=text), exp


def softmax_invoke(
    *,
    instance_name: str,
    parent_x_packed: str,
    parent_mask_signal: str,
    parent_clk: str, parent_rst: str, parent_start: str,
    K: int, abits: int = 8, obits: int = 8,
    exp_in_bits: int = 8, exp_out_bits: int = 12,
    exp_in_q_frac_bits: int = 4,
    exp_in_clamp: tuple[float, float] = (-16.0, 0.0),
    recip_lut_bits: int = 12,
    recip_out_frac_bits: int = 16,
    output_shift: int = 8,
    y_signal: str | None = None, done_signal: str | None = None,
) -> tuple[list[RawSubmodule], list[Gate]]:
    sm, exp = softmax_block(
        K=K, abits=abits, obits=obits,
        exp_in_bits=exp_in_bits, exp_out_bits=exp_out_bits,
        exp_in_q_frac_bits=exp_in_q_frac_bits, exp_in_clamp=exp_in_clamp,
        recip_lut_bits=recip_lut_bits,
        recip_out_frac_bits=recip_out_frac_bits,
        output_shift=output_shift,
    )
    if y_signal is None: y_signal = f"{instance_name}_y_packed"
    if done_signal is None: done_signal = f"{instance_name}_done"
    gates = [
        Gate(name=done_signal, kind="extern_wire", output_width=1),
        Gate(
            name=y_signal, kind="instance",
            inputs=[parent_clk, parent_rst, parent_start, parent_x_packed,
                    parent_mask_signal],
            attrs={
                "module_name": sm.top, "instance_name": instance_name,
                "input_ports": ["clk", "rst", "start", "x_packed", "mask"],
                "output_port": "y_packed",
                "extra_output_ports": [("done", done_signal)],
            },
            output_width=K * obits, output_signed=False,
        ),
    ]
    return [sm, exp], gates
