"""LUT-based fixed-point tanh.

Tanh saturates outside roughly [-4, 4] (tanh(4) is within 1e-3 of 1). The
LUT clamps inputs to a configurable range and indexes a small ROM. Output
is *signed* ``out_bits`` Q1.``out_bits-1`` (the value ``raw / 2**(out_bits-1)``;
range [-1, 1)). This is the structural difference vs ``sigmoid_block``, whose
output is unsigned Q0.``out_bits`` over [0, 1).

Default: 8-bit signed input clamped to [-4, 3.9375] (Q3.4), 256-entry LUT
of 8-bit signed outputs (Q1.7). 256 bytes per instance, combinational.

Generalises across LLaMA / Qwen / Mistral / GPT-2 (any model whose
``hidden_act`` involves tanh, e.g. GeLU's tanh approximation, or RNN gates).
"""
from __future__ import annotations

import math
from textwrap import dedent

from ..core import Gate, RawSubmodule


def tanh_module_name(in_bits: int, out_bits: int, in_q_frac_bits: int) -> str:
    return f"tanh_lut_in{in_bits}f{in_q_frac_bits}_out{out_bits}"


def tanh_block(
    *,
    in_bits: int = 8,
    out_bits: int = 8,
    in_q_frac_bits: int = 4,
    in_clamp: tuple[float, float] = (-4.0, 4.0),
    module_suffix: str = "",
) -> RawSubmodule:
    """Combinational tanh LUT.

    in_bits:        signed input width
    out_bits:       signed output width (Q1.(out_bits-1)); range [-1, 1).
    in_q_frac_bits: number of fractional bits in the input (the input
                    represents x = raw / 2**in_q_frac_bits)
    in_clamp:       clamp (lo, hi) applied to the dequantised input before
                    LUT lookup. Values outside this range pin to the LUT
                    extremes (tanh is essentially -1 / +1 there).
    """
    if in_bits < 2 or out_bits < 2:
        raise ValueError("bit widths too small")
    n_entries = 1 << in_bits
    out_max = (1 << (out_bits - 1)) - 1
    out_min = -(1 << (out_bits - 1))
    out_mask = (1 << out_bits) - 1

    base = tanh_module_name(in_bits, out_bits, in_q_frac_bits)
    name = base + (f"_{module_suffix}" if module_suffix else "")

    # Build the LUT contents indexed by the unsigned representation of
    # the signed input (i.e. two's-complement bit pattern).
    lut: list[int] = []
    for raw in range(n_entries):
        if raw & (1 << (in_bits - 1)):
            sint = raw - (1 << in_bits)
        else:
            sint = raw
        x = sint / (1 << in_q_frac_bits)
        x = max(in_clamp[0], min(in_clamp[1], x))
        v = math.tanh(x)
        # tanh(+inf) = 1.0 -> out_max (cap one short of 2**(out_bits-1) so
        # the value stays in signed range).
        out_int = max(out_min, min(out_max, round(v * (1 << (out_bits - 1)))))
        lut.append(out_int & out_mask)

    init_lines = "\n".join(
        f"    rom[{i}] = {out_bits}'h{lut[i]:x};" for i in range(n_entries)
    )
    text = dedent(f"""\
        // Generated by safetensors2verilog.blocks.tanh.
        // LUT-based tanh. in_bits={in_bits} (signed Q{in_bits-in_q_frac_bits-1}.{in_q_frac_bits}),
        // out_bits={out_bits} (signed Q1.{out_bits-1}; range [-1, 1)).
        // ROM size: {n_entries} entries x {out_bits} bits = {n_entries * out_bits // 8} bytes.

        `default_nettype none

        module {name} (
          input  wire signed [{in_bits-1}:0] x,
          output wire signed [{out_bits-1}:0] y
        );
          (* ram_style = "block" *)
          reg [{out_bits-1}:0] rom [0:{n_entries-1}];
          initial begin
        {init_lines}
          end
          // Index by unsigned bit pattern of x; tanh LUT is precomputed
          // in two's-complement order so this is a direct lookup.
          assign y = $signed(rom[x[{in_bits-1}:0]]);
        endmodule

        `default_nettype wire
        """)

    return RawSubmodule(top=name, text=text)


def tanh_invoke(
    *,
    instance_name: str,
    parent_x_signal: str,
    in_bits: int = 8,
    out_bits: int = 8,
    in_q_frac_bits: int = 4,
    in_clamp: tuple[float, float] = (-4.0, 4.0),
    y_signal: str | None = None,
) -> tuple[RawSubmodule, list[Gate]]:
    """Returns (submodule, [instance gate]).

    Mirror of ``sigmoid_invoke`` with signed Q1.(out_bits-1) output instead
    of unsigned Q0.out_bits.
    """
    sub = tanh_block(
        in_bits=in_bits, out_bits=out_bits,
        in_q_frac_bits=in_q_frac_bits, in_clamp=in_clamp,
    )
    if y_signal is None:
        y_signal = f"{instance_name}_y"
    gates = [
        Gate(
            name=y_signal,
            kind="instance",
            inputs=[parent_x_signal],
            attrs={
                "module_name": sub.top,
                "instance_name": instance_name,
                "input_ports": ["x"],
                "output_port": "y",
            },
            output_width=out_bits,
            output_signed=True,
        ),
    ]
    return sub, gates
