"""Command-line entry point.

  python -m safetensors2verilog input.safetensors --frontend NAME [-o out.v] [...]

Per-frontend flags are surfaced from `Frontend.options()`. To list the
registered frontends:

  python -m safetensors2verilog --list-frontends

To list a frontend's specific flags:

  python -m safetensors2verilog --list-frontend-options threshold_logic
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

# Importing this submodule has the side effect of registering frontends.
from . import frontends  # noqa: F401
from .core import FrontendOption, GateGraph, registry
from .verilog import emit_bram_template, emit_module


def _graph_to_jsonable(graph: GateGraph) -> dict:
    """Render a GateGraph as a plain dict for --emit-ir json output."""
    return {
        "top": graph.top,
        "inputs": [
            {"name": s.name, "width": s.width, "signed": s.signed,
             "direction": s.direction, "is_parameter": s.is_parameter}
            for s in graph.inputs
        ],
        "outputs": [
            {"name": s.name, "width": s.width, "signed": s.signed,
             "direction": s.direction}
            for s in graph.outputs
        ],
        "gates": [
            {
                "name": g.name,
                "kind": g.kind,
                "inputs": list(g.inputs),
                "attrs": g.attrs,
                "output_width": g.output_width,
                "output_signed": g.output_signed,
            }
            for g in graph.gates
        ],
    }


def _emit_sdc_template(graph: GateGraph, period_ns: float) -> str:
    """Synopsys Design Constraints starter file for the given graph.

    Produces:
      - one ``create_clock`` per distinct clock signal used by register
        gates (multi-clock support),
      - per-port input / output delay constraints (each port differentiated;
        excludes clk and rst sets),
      - false-path declarations between every pair of distinct clock
        domains (so async-domain crossings don't break STA),
      - false-path declarations on async resets.

    Multiple clock domains are inferred via ``collect_clocks(graph)`` in
    ``safetensors2verilog.verilog``.
    """
    from .verilog import collect_clocks, collect_resets
    clocks = sorted(collect_clocks(graph))
    resets = sorted(collect_resets(graph))
    has_register = any(g.kind == "register" for g in graph.gates)

    # If no register gates declared a clk, but the design has 'clk' as an
    # explicit input, fall back to that.
    if not clocks and any(s.name == "clk" for s in graph.inputs):
        clocks = ["clk"]

    in_delay = period_ns * 0.4
    out_delay = period_ns * 0.4
    lines = [
        "# Generated by safetensors2verilog. SDC starter — tune for your target.",
        f"# Module: {graph.top}",
        "",
    ]
    if not clocks and not has_register:
        lines.append("# (no clock signals detected; SDC mostly empty)")
        lines.append("")
        return "\n".join(lines)

    # ---- Clocks ----
    primary_clk = clocks[0] if clocks else "clk"
    for clk in clocks:
        # Different clocks may belong to different domains; the user can
        # adjust the period per clock as needed.
        lines.append(
            f"create_clock -name {clk} -period {period_ns} [get_ports {clk}]"
        )
    lines.append("")

    # ---- Per-port input / output delays (anchored to the primary clock) ----
    lines.append(
        f"# Per-port I/O delays (anchored to primary clock '{primary_clk}')."
    )
    excluded = set(clocks) | set(resets) | {"rst"}
    for s in graph.inputs:
        if s.name in excluded or s.is_parameter:
            continue
        lines.append(
            f"set_input_delay  -clock {primary_clk} -max {in_delay:.2f} "
            f"[get_ports {s.name}]"
        )
    for s in graph.outputs:
        lines.append(
            f"set_output_delay -clock {primary_clk} -max {out_delay:.2f} "
            f"[get_ports {s.name}]"
        )
    lines.append("")

    # ---- Cross-clock-domain false paths ----
    if len(clocks) > 1:
        lines.append("# Cross-clock-domain false paths (no STA across boundaries).")
        for i, ci in enumerate(clocks):
            for cj in clocks[i+1:]:
                lines.append(
                    f"set_false_path -from [get_clocks {ci}] "
                    f"-to [get_clocks {cj}]"
                )
                lines.append(
                    f"set_false_path -from [get_clocks {cj}] "
                    f"-to [get_clocks {ci}]"
                )
        lines.append("")

    # ---- Async resets ----
    if resets:
        lines.append("# Asynchronous resets; do not analyze their timing.")
        for r in resets:
            lines.append(
                f"set_false_path -from [get_ports {r}] -to [all_registers]"
            )
        lines.append("")

    return "\n".join(lines)


def _format_port_contract(graph: GateGraph) -> str:
    """Render the GateGraph's port surface as a human-readable contract."""
    lines: list[str] = []
    lines.append(f"# port contract for {graph.top}")
    lines.append("")
    lines.append(f"## inputs ({len(graph.inputs)})")
    for s in graph.inputs:
        suffix = ""
        if s.width != 1:
            suffix += f" [{s.width-1}:0]"
        if s.signed:
            suffix += " signed"
        if s.is_parameter:
            suffix += f" parameter (default={s.parameter_value})"
        lines.append(f"  {s.name}{suffix}")
    lines.append("")
    lines.append(f"## outputs ({len(graph.outputs)})")
    for s in graph.outputs:
        suffix = f" [{s.width-1}:0]" if s.width != 1 else ""
        if s.signed:
            suffix += " signed"
        lines.append(f"  {s.name}{suffix}")
    lines.append("")
    lines.append(f"## gates: {len(graph.gates)}")
    return "\n".join(lines) + "\n"


def _apply_top_outputs_filter(graph: GateGraph, spec: str) -> GateGraph:
    """Trim ``graph.outputs`` to only the signals matching ``spec``.

    Names in ``spec`` are substring-matched against output port names
    (after the frontend has computed them). Any output not matching is
    dropped from the module's port list and becomes an internal wire.
    Gate definitions and topological order are preserved.

    Raising on an empty match would force the user into a discovery
    loop; we instead emit a warning and keep all outputs so the
    accidental typo doesn't silently produce a portless module.
    """
    import warnings

    from .core import Signal

    requested = [t for t in spec.replace(",", " ").split() if t]
    if not requested:
        return graph

    import re
    def _candidates(name: str) -> tuple[str, str]:
        # Match against the raw signal name and the Verilog-sanitized
        # form, so users can paste either '.' or '_' separated names.
        return name, re.sub(r"[^A-Za-z0-9_]", "_", name)

    keep: list[Signal] = []
    matched: set[str] = set()
    for s in graph.outputs:
        cands = _candidates(s.name)
        if any(req in c for req in requested for c in cands):
            keep.append(s)
            matched.add(s.name)

    missed = [
        r for r in requested
        if not any(r in c for s in graph.outputs for c in _candidates(s.name))
    ]
    if missed:
        warnings.warn(
            f"--top-outputs: no output port name contains "
            f"{missed!r}; ignoring those terms",
            UserWarning, stacklevel=2,
        )
    if not keep:
        warnings.warn(
            "--top-outputs: nothing matched; falling back to original outputs",
            UserWarning, stacklevel=2,
        )
        return graph

    return GateGraph(
        inputs=graph.inputs, outputs=keep, gates=graph.gates, top=graph.top
    )


_METADATA_HEADER_EXCLUDED = frozenset({
    "signal_registry",         # too large to render in a comment
    "schema_version",           # internal bookkeeping
    "format", "encoding", "version",
})


def _render_metadata_header(input_path: Path) -> str:
    """Read non-reserved metadata from a safetensors file and render it
    as a `// key: value` Verilog comment block.

    Returns "" when there is nothing to render. Long values are truncated
    at 200 characters per line so the header remains readable.
    """
    try:
        from safetensors import safe_open
        with safe_open(str(input_path), framework="pt") as f:
            meta = f.metadata() or {}
    except Exception:
        return ""

    keep = [
        (k, v) for k, v in sorted(meta.items())
        if k not in _METADATA_HEADER_EXCLUDED
        and not k.startswith("threshold_logic.signal_registry")
    ]
    if not keep:
        return ""

    lines = ["// ---- safetensors metadata passthrough ----"]
    for k, v in keep:
        text = str(v).replace("\n", " ").replace("\r", " ")
        if len(text) > 200:
            text = text[:197] + "..."
        lines.append(f"// {k}: {text}")
    lines.append("// ---- end metadata ----")
    lines.append("")
    return "\n".join(lines) + "\n"


def _emit_diagnostic(message: str, level: str, fmt: str, file=sys.stderr) -> None:
    """Emit one diagnostic message in either plain text or JSON form."""
    if fmt == "json":
        print(json.dumps({"level": level, "message": message}), file=file)
    else:
        print(message, file=file)


def _add_frontend_options(
    parser: argparse.ArgumentParser, opts: list[FrontendOption]
) -> None:
    for opt in opts:
        flag = "--" + opt.name
        kwargs: dict = {"help": opt.help, "default": opt.default}
        if opt.type is bool:
            kwargs["action"] = "store_true"
        else:
            kwargs["type"] = opt.type
            if opt.metavar:
                kwargs["metavar"] = opt.metavar
        parser.add_argument(flag, **kwargs)


def _format_option_default(opt: FrontendOption) -> str:
    if opt.type is bool:
        return f"flag (default: {bool(opt.default)})"
    if opt.default is None:
        return f"{opt.type.__name__} (no default)"
    return f"{opt.type.__name__} (default: {opt.default!r})"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        prog="safetensors2verilog",
        description="Compile safetensors-stored networks to synthesis-ready Verilog.",
        # Disable argparse prefix matching so frontend flags like
        # ``--pipeline`` can't be silently rebound to ``--pipeline-every``.
        allow_abbrev=False,
    )
    parser.add_argument(
        "input", nargs="?", type=Path, help="path to .safetensors file"
    )
    parser.add_argument(
        "-o", "--output", type=Path, default=None,
        help="output Verilog file (default: stdout)",
    )
    parser.add_argument(
        "--frontend", type=str, default="threshold_logic",
        help="frontend module name (default: threshold_logic)",
    )
    parser.add_argument(
        "--top", type=str, default="top",
        help="top-level Verilog module name (default: top)",
    )
    parser.add_argument(
        "--list-frontends", action="store_true",
        help="print registered frontends and exit",
    )
    parser.add_argument(
        "--list-frontend-options", type=str, metavar="FRONTEND",
        help="print options accepted by a specific frontend and exit",
    )
    parser.add_argument(
        "--emit-bram-template", type=Path, default=None, metavar="PATH",
        help=(
            "alongside the main output, write a synchronous BRAM template "
            "(single-port read/write, configurable address width)."
        ),
    )
    parser.add_argument(
        "--bram-addr-bits", type=int, default=None,
        help=(
            "address width for --emit-bram-template (default: read from "
            "manifest.addr_bits when present, else 16)."
        ),
    )
    parser.add_argument(
        "--bram-data-bits", type=int, default=8,
        help="data width for --emit-bram-template (default: 8)",
    )
    parser.add_argument(
        "--emit-ir", choices=["json"], default=None,
        help=(
            "instead of (or alongside) Verilog, dump the IR as JSON. "
            "Goes to --output if set, otherwise stdout."
        ),
    )
    parser.add_argument(
        "--dry-run", action="store_true",
        help=(
            "parse and validate the input but emit nothing. Useful for "
            "checking that a frontend accepts a given safetensors file."
        ),
    )
    parser.add_argument(
        "--inspect", action="store_true",
        help=(
            "after parsing (combine with --circuit to scope), print the "
            "external port contract — every input and output the module "
            "exposes, with widths and signedness. Use this to discover "
            "that, e.g., 'float16.add' is the mantissa-add stage and "
            "takes 15 inputs, not 32. Goes to stdout (or --output)."
        ),
    )
    parser.add_argument(
        "-q", "--quiet", action="store_true",
        help="suppress progress messages on stderr.",
    )
    parser.add_argument(
        "--target", choices=["verilog", "sv"], default="verilog",
        help="output dialect (default: verilog). 'sv' rewrites to "
             "SystemVerilog idioms (logic, always_ff, always_comb).",
    )
    parser.add_argument(
        "--diag-format", choices=["text", "json"], default="text",
        help="emit diagnostics (warnings, info messages) as plain text "
             "(default) or as line-delimited JSON on stderr.",
    )
    parser.add_argument(
        "--emit-sdc", type=Path, default=None, metavar="PATH",
        help="alongside the main output, write a Synopsys Design "
             "Constraints (SDC) starter with one default clock and "
             "I/O timing constraints. Tweak it per your target board.",
    )
    parser.add_argument(
        "--sdc-period-ns", type=float, default=10.0,
        help="default clock period for --emit-sdc in nanoseconds "
             "(default: 10.0, i.e. 100 MHz).",
    )
    parser.add_argument(
        "--pipeline-every", type=int, default=None, metavar="N",
        help=(
            "insert a pipeline register every N combinational depths. "
            "Each cut adds 1 cycle of latency; the critical path shrinks "
            "to N levels. The user must drive 'clk' from outside. "
            "Useful when threshold-network depth (try --report) exceeds "
            "what the target FPGA can close at the desired clock."
        ),
    )
    parser.add_argument(
        "--group-ports", action="store_true",
        help=(
            "in the emitted module's port list, group ports by their "
            "leading dotted prefix and insert '// -- <prefix> --' "
            "comment dividers. Same semantics, much shorter visual "
            "diffs. Recommended whenever the port count exceeds a few "
            "dozen."
        ),
    )
    parser.add_argument(
        "--pack-buses", action="store_true",
        help=(
            "detect external input ports of the form '<base>[i]' for "
            "contiguous indices 0..N-1 and emit them as a single packed "
            "Verilog bus 'input wire [N-1:0] base'. References inside "
            "the body resolve to bit-selects on the bus. Off by default "
            "for backward compatibility with downstream tools that "
            "depend on the flat per-bit port list."
        ),
    )
    parser.add_argument(
        "--equiv-check", action="store_true",
        help=(
            "after writing Verilog, build a self-checking testbench from "
            "the in-memory GateGraph (Python evaluator), compile it with "
            "iverilog, and report PASS/FAIL counts. Threshold-logic "
            "frontend only. Requires iverilog and vvp on PATH and "
            "--output to be set."
        ),
    )
    parser.add_argument(
        "--equiv-max-exhaustive", type=int, default=16, metavar="N",
        help="max external inputs for which --equiv-check uses exhaustive "
             "enumeration (default: 16). Beyond this, falls back to "
             "--equiv-sample random cases.",
    )
    parser.add_argument(
        "--equiv-sample", type=int, default=1024, metavar="N",
        help="number of random samples for --equiv-check on circuits "
             "wider than --equiv-max-exhaustive (default: 1024).",
    )
    parser.add_argument(
        "--emit-sby-equiv", type=Path, default=None, metavar="PATH",
        help=(
            "alongside the main output, write a SymbiYosys equiv task "
            "script comparing the emitted Verilog against itself; the "
            "user replaces one of the [files] entries with a reference "
            "implementation to formally check equivalence."
        ),
    )
    parser.add_argument(
        "--synth-stats", action="store_true",
        help=(
            "after writing Verilog, run yosys+abc on it and print "
            "post-tech-map gate counts and a LUT4 estimate. Yosys "
            "must be on PATH (--yosys-path overrides). Requires "
            "--output to be set."
        ),
    )
    parser.add_argument(
        "--yosys-path", type=str, default=None, metavar="PATH",
        help="explicit path to yosys executable for --synth-stats",
    )
    parser.add_argument(
        "--report", choices=["text", "json"], default=None,
        help=(
            "after parsing, print a static-analysis report to stderr "
            "(critical-path depth, fanout, gate-kind histogram). "
            "Does not affect Verilog emission."
        ),
    )
    parser.add_argument(
        "--top-outputs", type=str, default=None, metavar="NAMES",
        help=(
            "comma- or whitespace-separated list of signal names that "
            "should remain as top-level module outputs. Every other "
            "internal gate is demoted to a wire. Substring match: "
            "'fa7_ha2_sum_layer2,fa7_carry_or' keeps just the eight "
            "sum bits and the final carry of an 8-bit ripple-carry. "
            "Without this flag, every signal not consumed by another "
            "gate is promoted to a top-level output (the default the "
            "frontend computes)."
        ),
    )
    parser.add_argument(
        "--metadata-passthrough", action="store_true",
        help=(
            "copy non-reserved safetensors metadata into a Verilog "
            "header comment block at the top of the output file. "
            "Reserved keys (signal_registry, schema_version, internal "
            "frontend bookkeeping) are excluded; everything else is "
            "rendered as // key: value lines. Use this to preserve "
            "model provenance, training notes, license tags, etc., "
            "through the compile step."
        ),
    )
    parser.add_argument(
        "--list-circuits", action="store_true",
        help=(
            "list every circuit prefix present in the input safetensors "
            "file and exit. Threshold-logic frontend only. Useful for "
            "discovering valid --circuit values."
        ),
    )
    parser.add_argument(
        "--emit-instantiation", type=Path, default=None, metavar="PATH",
        help=(
            "alongside the main output, write a Verilog instantiation "
            "template for the emitted module: a paste-ready '<module> "
            "u_inst (.port(parent_signal), ...)' snippet that the user "
            "drops into a wrapper. Useful when a frontend produces a "
            "parameterised module the user instantiates several times."
        ),
    )
    parser.add_argument(
        "--emit-vivado-tcl", type=Path, default=None, metavar="PATH",
        help=(
            "alongside the main output, write a Vivado batch-mode Tcl "
            "script that runs synth_design + place_design + route_design "
            "and emits utilization + timing reports. Use --vivado-part to "
            "specify the FPGA device."
        ),
    )
    parser.add_argument(
        "--vivado-part", type=str, default="xcvu9p-flga2104-2L-e",
        help="Vivado part for --emit-vivado-tcl (default: xcvu9p-flga2104-2L-e).",
    )
    parser.add_argument(
        "--emit-quartus", type=Path, default=None, metavar="PATH_PREFIX",
        help=(
            "alongside the main output, write Quartus QSF + SDC + TCL "
            "files at <PATH_PREFIX>.qsf / .sdc / _flow.tcl driving a "
            "full quartus_sh -t synth + place + route flow."
        ),
    )
    parser.add_argument(
        "--quartus-part", type=str, default="1SG280HU2F50E2VG",
        help="Quartus device (default: 1SG280HU2F50E2VG, Stratix 10).",
    )
    parser.add_argument(
        "--emit-synopsys-dc-tcl", type=Path, default=None, metavar="PATH",
        help=(
            "alongside the main output, write a Synopsys Design Compiler "
            "Tcl script that runs compile_ultra and emits area + timing "
            "reports."
        ),
    )
    parser.add_argument(
        "--synopsys-library", type=str, default="slow_typical_corner.db",
        help="Synopsys technology library for --emit-synopsys-dc-tcl.",
    )
    parser.add_argument(
        "--emit-multi", type=Path, default=None, metavar="DIR",
        help=(
            "use Frontend.parse_multi to enumerate every top module the "
            "frontend exports, and write one <top>.v file per returned "
            "graph under DIR. Most frontends still emit a single graph; "
            "frontends that override parse_multi (multi-circuit, "
            "multi-head-export, etc.) get one .v per top. Mutually "
            "exclusive with -o."
        ),
    )
    parser.add_argument(
        "--sidecar-layout", choices=["flat", "subdirs", "tarball"],
        default=None,
        help=(
            "when the frontend emits sidecar weight ROMs (matmul / "
            "embedding / streaming-matmul), write them under --output's "
            "parent directory using one of three layouts: 'flat' (legacy; "
            "all hex files alongside the .v), 'subdirs' (recommended at "
            "scale: per-module subdirectory), or 'tarball' (one tar archive "
            "next to the .v, no individual files extracted). A "
            "manifest.json is written in either case mapping submodule -> "
            "sidecar file list. Without this flag, sidecar files are not "
            "auto-written."
        ),
    )
    parser.add_argument(
        "--sidecar-tarball", type=Path, default=None, metavar="PATH",
        help=(
            "when --sidecar-layout=tarball, the path of the output archive. "
            "Defaults to <output>.sidecars.tar."
        ),
    )
    parser.add_argument(
        "--circuit", action="append", default=None, metavar="PREFIX",
        help=(
            "extract a single named circuit (with dependency closure) "
            "from the input safetensors before compiling. May be passed "
            "multiple times to extract several circuits at once. PREFIX "
            "matches a gate whose name equals or is a dotted descendant "
            "of the prefix (e.g. 'arithmetic.ripplecarry8bit'). "
            "Threshold-logic frontend only."
        ),
    )

    # Two-pass parsing: pull out the frontend name first, then add its
    # options and reparse so per-frontend flags appear in --help and bind
    # cleanly when the user runs e.g.
    #   safetensors2verilog ... --frontend threshold_logic --skip-memory
    args, _ = parser.parse_known_args(argv)

    if args.list_frontends:
        for name, desc in registry.names():
            print(f"  {name:<24}  {desc}")
        return 0

    if args.list_frontend_options:
        try:
            cls = registry.get(args.list_frontend_options)
        except KeyError as e:
            parser.error(str(e))
            return 2
        opts = cls.options()
        if not opts:
            print(f"frontend '{cls.name}' has no options.")
            return 0
        print(f"options for frontend '{cls.name}':")
        for o in opts:
            print(f"  --{o.name:<22}  {_format_option_default(o)}")
            if o.help:
                print(f"      {o.help}")
        return 0

    if args.input is None:
        parser.error("input safetensors path is required (or use --list-frontends)")
    if not args.input.exists():
        parser.error(f"file not found: {args.input}")

    if args.list_circuits:
        from safetensors import safe_open
        prefixes: set[str] = set()
        suffixes = (".weight", ".bias", ".inputs")
        with safe_open(str(args.input), framework="pt") as f:
            for k in f.keys():
                for suf in suffixes:
                    if k.endswith(suf):
                        gate = k[: -len(suf)]
                        if gate.startswith("manifest."):
                            break
                        # Group by first 2 dotted segments
                        parts = gate.split(".")
                        prefixes.add(".".join(parts[:2]) if len(parts) >= 2 else gate)
                        break
        for p in sorted(prefixes):
            print(p)
        return 0

    try:
        frontend_cls = registry.get(args.frontend)
    except KeyError as e:
        parser.error(str(e))
        return 2

    _add_frontend_options(parser, frontend_cls.options())
    args = parser.parse_args(argv)

    fe_kwargs = {}
    for opt in frontend_cls.options():
        attr = opt.name.replace("-", "_")
        fe_kwargs[attr] = getattr(args, attr)

    if args.diag_format == "json":
        import warnings as _warnings

        def _showwarning_json(message, category, filename, lineno,
                              file=None, line=None):
            payload = json.dumps({
                "level": "warning",
                "category": getattr(category, "__name__", str(category)),
                "message": str(message),
                "file": str(filename),
                "line": lineno,
            })
            print(payload, file=file or sys.stderr)

        _warnings.showwarning = _showwarning_json

    # --circuit triggers dependency-closure extraction into a temp file,
    # which is then handed to the frontend's normal parse() path.
    parse_path = args.input
    cleanup_temp: Path | None = None
    if args.circuit:
        if args.frontend != "threshold_logic":
            parser.error(
                "--circuit is only supported with --frontend threshold_logic"
            )
        import tempfile

        from .extract import extract_subset
        tmpdir = Path(tempfile.mkdtemp(prefix="s2v_extract_"))
        cleanup_temp = tmpdir
        parse_path = tmpdir / "subset.safetensors"
        try:
            extract_subset(
                args.input, list(args.circuit), parse_path,
                quiet=args.quiet,
            )
        except ValueError as e:
            parser.error(str(e))
            return 2

    if args.emit_multi is not None and args.output is not None:
        parser.error("--emit-multi and -o are mutually exclusive")
        return 2

    frontend = frontend_cls()
    try:
        if args.emit_multi is not None:
            graphs = frontend.parse_multi(
                parse_path, top=args.top, **fe_kwargs
            )
            if not graphs:
                parser.error("frontend.parse_multi returned no graphs")
                return 2
            # Pick the first as the "primary" graph for downstream
            # operations (--report, --inspect, --equiv-check) that need a
            # single graph reference; --emit-multi writes all of them.
            graph = graphs[0]
        else:
            graph = frontend.parse(parse_path, top=args.top, **fe_kwargs)
            graphs = [graph]
    finally:
        if cleanup_temp is not None:
            import shutil
            shutil.rmtree(cleanup_temp, ignore_errors=True)

    def _info(msg: str) -> None:
        if not args.quiet:
            print(msg, file=sys.stderr)

    if args.top_outputs:
        graph = _apply_top_outputs_filter(graph, args.top_outputs)
        _info(
            f"--top-outputs trimmed module to {len(graph.outputs)} output(s)"
        )

    if args.pipeline_every is not None and args.pipeline_every > 0:
        from .transforms import pipeline_every
        before_gates = len(graph.gates)
        graph = pipeline_every(graph, args.pipeline_every)
        _info(
            f"--pipeline-every {args.pipeline_every}: inserted "
            f"{len(graph.gates) - before_gates} register(s)"
        )

    if args.report:
        from .analysis import format_summary, summary
        if args.report == "json":
            print(json.dumps(summary(graph), indent=2), file=sys.stderr)
        else:
            print(format_summary(graph), file=sys.stderr)

    if args.dry_run:
        _info(
            f"dry-run: {len(graph.gates)} gates, {len(graph.inputs)} inputs, "
            f"{len(graph.outputs)} outputs"
        )
        return 0

    if args.inspect:
        report = _format_port_contract(graph)
        if args.output is None:
            sys.stdout.write(report)
        else:
            args.output.parent.mkdir(parents=True, exist_ok=True)
            args.output.write_text(report, encoding="utf-8")
            _info(f"wrote {args.output} (port contract)")
        return 0

    if args.emit_ir == "json":
        text = json.dumps(_graph_to_jsonable(graph), indent=2)
    else:
        text = emit_module(graph, target=args.target,
                           pack_buses=args.pack_buses,
                           group_ports=args.group_ports)
        if args.metadata_passthrough:
            header = _render_metadata_header(args.input)
            if header:
                text = header + text

    if args.emit_multi is not None:
        args.emit_multi.mkdir(parents=True, exist_ok=True)
        for sub_graph in graphs:
            sub_text = emit_module(
                sub_graph, target=args.target,
                pack_buses=args.pack_buses,
                group_ports=args.group_ports,
            )
            if args.metadata_passthrough:
                header = _render_metadata_header(args.input)
                if header:
                    sub_text = header + sub_text
            ext = ".sv" if args.target == "sv" else ".v"
            out_path = args.emit_multi / f"{sub_graph.top}{ext}"
            out_path.write_text(sub_text, encoding="utf-8")
            _info(
                f"wrote {out_path} ({len(sub_graph.gates)} gates, "
                f"{len(sub_graph.inputs)} inputs, "
                f"{len(sub_graph.outputs)} outputs)"
            )
    elif args.output is None:
        sys.stdout.write(text)
    else:
        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_text(text, encoding="utf-8")
        _info(
            f"wrote {args.output} ({len(graph.gates)} gates, "
            f"{len(graph.inputs)} inputs, {len(graph.outputs)} outputs)"
        )

    if args.sidecar_layout is not None and args.output is not None:
        from .core import write_sidecar_files
        sidecar_dir = args.output.parent
        tarball_path = (
            args.sidecar_tarball
            if args.sidecar_tarball is not None
            else args.output.with_suffix(args.output.suffix + ".sidecars.tar")
        )
        stats = write_sidecar_files(
            graph, sidecar_dir,
            layout=args.sidecar_layout,
            tarball_path=tarball_path if args.sidecar_layout == "tarball" else None,
        )
        _info(
            f"wrote {stats['files']} sidecar file(s) across "
            f"{stats['modules']} module(s) ({stats['bytes']/1024:.1f} KB) "
            f"using layout '{args.sidecar_layout}'"
        )

    if args.emit_sdc is not None:
        sdc_text = _emit_sdc_template(graph, args.sdc_period_ns)
        args.emit_sdc.parent.mkdir(parents=True, exist_ok=True)
        args.emit_sdc.write_text(sdc_text, encoding="utf-8")
        _info(
            f"wrote {args.emit_sdc} (SDC, "
            f"{args.sdc_period_ns} ns clock period)"
        )

    if args.emit_instantiation is not None:
        from .verilog import emit_instantiation_template
        snippet = emit_instantiation_template(graph)
        args.emit_instantiation.parent.mkdir(parents=True, exist_ok=True)
        args.emit_instantiation.write_text(snippet, encoding="utf-8")
        _info(
            f"wrote {args.emit_instantiation} (instantiation template "
            f"for {graph.top})"
        )

    if args.emit_vivado_tcl is not None and args.output is not None:
        from .synth_vendor import emit_vivado_tcl
        tcl = emit_vivado_tcl(
            args.output, top=graph.top, part=args.vivado_part,
            period_ns=args.sdc_period_ns,
        )
        args.emit_vivado_tcl.parent.mkdir(parents=True, exist_ok=True)
        args.emit_vivado_tcl.write_text(tcl, encoding="utf-8")
        _info(
            f"wrote {args.emit_vivado_tcl} (Vivado batch Tcl, "
            f"part={args.vivado_part})"
        )

    if args.emit_quartus is not None and args.output is not None:
        from .synth_vendor import emit_quartus_qsf
        bundle = emit_quartus_qsf(
            args.output, top=graph.top, part=args.quartus_part,
            period_ns=args.sdc_period_ns,
        )
        prefix = args.emit_quartus
        prefix.parent.mkdir(parents=True, exist_ok=True)
        prefix.with_suffix(".qsf").write_text(
            bundle[".qsf"], encoding="utf-8")
        prefix.with_suffix(".sdc").write_text(
            bundle[".sdc"], encoding="utf-8")
        prefix.with_suffix(".tcl").write_text(
            bundle[".tcl"], encoding="utf-8")
        _info(
            f"wrote {prefix.with_suffix('.qsf')} / .sdc / .tcl "
            f"(Quartus full flow, part={args.quartus_part})"
        )

    if args.emit_synopsys_dc_tcl is not None and args.output is not None:
        from .synth_vendor import emit_synopsys_dc_tcl
        tcl = emit_synopsys_dc_tcl(
            args.output, top=graph.top, library=args.synopsys_library,
            period_ns=args.sdc_period_ns,
        )
        args.emit_synopsys_dc_tcl.parent.mkdir(parents=True, exist_ok=True)
        args.emit_synopsys_dc_tcl.write_text(tcl, encoding="utf-8")
        _info(
            f"wrote {args.emit_synopsys_dc_tcl} (Synopsys DC Tcl, "
            f"library={args.synopsys_library})"
        )

    if args.equiv_check:
        if args.frontend != "threshold_logic":
            parser.error(
                "--equiv-check is only supported with --frontend threshold_logic"
            )
            return 2
        if args.output is None:
            parser.error("--equiv-check requires --output")
            return 2
        from .equivalence import run_iverilog_check
        try:
            result = run_iverilog_check(
                graph, text, dut_module=graph.top,
                max_exhaustive=args.equiv_max_exhaustive,
                sample_size=args.equiv_sample,
                pack_buses=args.pack_buses,
            )
        except (RuntimeError, FileNotFoundError) as e:
            _info(f"--equiv-check failed: {e}")
        else:
            verdict = "PASS" if result["passed"] else "FAIL"
            _info(
                f"--equiv-check: {verdict} {result['cases']} cases "
                f"({result['fails']} fail)"
            )

    if args.emit_sby_equiv is not None:
        from .equivalence import emit_sby_equiv
        sby = emit_sby_equiv(
            reference_v=str(args.output) if args.output else "reference.v",
            target_v=str(args.output) if args.output else "target.v",
            top=graph.top,
        )
        args.emit_sby_equiv.parent.mkdir(parents=True, exist_ok=True)
        args.emit_sby_equiv.write_text(sby, encoding="utf-8")
        _info(f"wrote {args.emit_sby_equiv} (SymbiYosys equiv task)")

    if args.synth_stats:
        if args.output is None:
            parser.error("--synth-stats requires --output")
            return 2
        from .synth import format_synth_report, run_synth
        try:
            stats = run_synth(
                args.output, top=graph.top, yosys=args.yosys_path,
            )
        except (RuntimeError, FileNotFoundError) as e:
            _info(f"--synth-stats failed: {e}")
        else:
            _info(format_synth_report(stats))

    if args.emit_bram_template is not None:
        addr_bits = args.bram_addr_bits
        if addr_bits is None:
            addr_bits = 16
            try:
                from safetensors import safe_open
                with safe_open(str(args.input), framework="pt") as f:
                    if "manifest.addr_bits" in f.keys():
                        addr_bits = int(f.get_tensor("manifest.addr_bits").item())
            except Exception as e:  # pragma: no cover - non-critical fallback
                _info(
                    f"warning: could not read manifest.addr_bits "
                    f"({type(e).__name__}: {e}); using default 16"
                )
        bram_text = emit_bram_template(
            addr_bits=addr_bits, data_bits=args.bram_data_bits
        )
        args.emit_bram_template.parent.mkdir(parents=True, exist_ok=True)
        args.emit_bram_template.write_text(bram_text, encoding="utf-8")
        _info(
            f"wrote {args.emit_bram_template} (BRAM template, "
            f"{addr_bits}-bit addr, {args.bram_data_bits}-bit data)"
        )

    return 0


if __name__ == "__main__":
    sys.exit(main())
