"""Pure-Python bit-stable reference forward pass for the LLaMA-architecture
1-token path the ``hf_llama`` frontend lowers to Verilog.

The Verilog generated by ``hf_llama`` uses fixed-point integer arithmetic
throughout: int8 activations and weights, int32 matmul accumulators,
LUT-driven sigmoid / silu / rsqrt / rope. This module is the Python
mirror: same int-arithmetic semantics, no float drift, suitable for
diffing against a verilator run line-for-line.

Use:

  hidden = llama_int_reference_one_layer(
      config=cfg, state_dict=sd, token_id=token_id, position=pos,
      requantize_params=cal_params,   # optional; uses heuristic shifts
                                       # when None
  )

Returns the per-channel int8 final_norm hidden state as a 1-D torch
int32 tensor of length ``hidden_size``. The Verilog's ``final_norm``
output should equal this element-by-element when both are driven with
the same token_id, position, and calibration.

The KV-cache is treated as empty / fresh per call (matching the
hf_llama frontend's first-token semantics); for autoregressive
multi-token decode use the multi-step driver (item 20).
"""
from __future__ import annotations

import math

import torch

from .calibration import (
    _gelu_int, _quantize_input_tokens, _quantize_per_channel_int,
    _rms_norm_int_reference, _silu_int,
)


def llama_int_reference_one_layer(
    *,
    config: dict,
    state_dict: dict[str, torch.Tensor],
    token_id: int,
    position: int = 0,
    abits: int = 8,
    weight_bits: int = 8,
    requantize_params: list[dict[str, dict[str, list[int]]]] | None = None,
) -> torch.Tensor:
    """Bit-stable int reference of one transformer layer + final_norm.

    Returns the post-final-norm hidden vector (length ``hidden_size``,
    int32 elements bounded to int8 range).

    The KV cache is treated as empty (this is the first-token path); RoPE
    is applied at the supplied ``position`` (default 0).
    """
    HID = int(config["hidden_size"])
    H = int(config["num_attention_heads"])
    KV = int(config.get("num_key_value_heads", H))
    INTER = int(config["intermediate_size"])
    EPS = float(config.get("rms_norm_eps", 1e-5))
    HIDDEN_ACT = config.get("hidden_act", "silu")
    D = HID // H

    if HIDDEN_ACT in ("silu", "swiglu"):
        act_fn = _silu_int
    elif HIDDEN_ACT == "gelu":
        act_fn = _gelu_int
    else:
        raise ValueError(f"unknown hidden_act={HIDDEN_ACT!r}")

    qmax_a = (1 << (abits - 1)) - 1
    embed_w = state_dict["model.embed_tokens.weight"].to(torch.float32)
    embed_q, _scale = _quantize_input_tokens(embed_w, abits)
    hidden = embed_q[int(token_id)].clone().to(torch.int32)

    Wq, _ = _quantize_per_channel_int(
        state_dict["model.layers.0.self_attn.q_proj.weight"],
        weight_bits=weight_bits)
    Wk, _ = _quantize_per_channel_int(
        state_dict["model.layers.0.self_attn.k_proj.weight"],
        weight_bits=weight_bits)
    Wv, _ = _quantize_per_channel_int(
        state_dict["model.layers.0.self_attn.v_proj.weight"],
        weight_bits=weight_bits)
    Wo, _ = _quantize_per_channel_int(
        state_dict["model.layers.0.self_attn.o_proj.weight"],
        weight_bits=weight_bits)
    Wg, _ = _quantize_per_channel_int(
        state_dict["model.layers.0.mlp.gate_proj.weight"],
        weight_bits=weight_bits)
    Wu, _ = _quantize_per_channel_int(
        state_dict["model.layers.0.mlp.up_proj.weight"],
        weight_bits=weight_bits)
    Wd, _ = _quantize_per_channel_int(
        state_dict["model.layers.0.mlp.down_proj.weight"],
        weight_bits=weight_bits)

    g1_t = state_dict["model.layers.0.input_layernorm.weight"].to(torch.float32)
    g2_t = state_dict["model.layers.0.post_attention_layernorm.weight"].to(torch.float32)
    gn_t = state_dict["model.norm.weight"].to(torch.float32)

    def gamma_to_int(t: torch.Tensor) -> list[int]:
        f = t.to(torch.float32)
        scale = 1 << 14
        qmax_g = (1 << 15) - 1
        return [
            max(-qmax_g - 1, min(qmax_g, int(round(v * scale))))
            for v in f.tolist()
        ]
    g1 = gamma_to_int(g1_t)
    g2 = gamma_to_int(g2_t)
    gn = gamma_to_int(gn_t)

    def chained(acc: torch.Tensor, layer: int, site: str) -> torch.Tensor:
        if requantize_params is not None:
            site_p = requantize_params[layer][site]
            muls_t = torch.tensor(site_p["muls"], dtype=torch.int64)
            shifts_l = list(site_p["shifts"])
            scaled = acc * muls_t
            out = torch.empty_like(acc)
            for ch in range(acc.shape[0]):
                sh = int(shifts_l[ch])
                v = int(scaled[ch].item())
                out[ch] = v >> sh if sh >= 0 else v << -sh
            return out.clamp(-qmax_a, qmax_a)
        # Heuristic shift fallback.
        K = acc.shape[0]
        sh = weight_bits + max(1, (K - 1).bit_length()) - 2
        return (acc >> sh).clamp(-qmax_a, qmax_a)

    norm1 = _rms_norm_int_reference(hidden, g1, gamma_bits=16,
                                     eps=EPS, abits=abits)
    q_acc = (Wq.to(torch.int64) @ norm1.to(torch.int64))
    k_acc = (Wk.to(torch.int64) @ norm1.to(torch.int64))
    v_acc = (Wv.to(torch.int64) @ norm1.to(torch.int64))
    q_int = chained(q_acc, 0, "q")
    v_int = chained(v_acc, 0, "v")

    # First-token attention is dominated by self-attention against the
    # single K/V; mirror the hardware's first-token path by tiling V
    # across the heads.
    attn_int = (
        v_int.view(KV, D)
        .repeat_interleave(H // KV, dim=0)
        .flatten()
        .clamp(-qmax_a, qmax_a)
    )

    o_acc = (Wo.to(torch.int64) @ attn_int.to(torch.int64))
    o_int = chained(o_acc, 0, "o")
    hidden = (hidden + o_int).clamp(-qmax_a, qmax_a)

    norm2 = _rms_norm_int_reference(hidden, g2, gamma_bits=16,
                                     eps=EPS, abits=abits)
    g_acc = (Wg.to(torch.int64) @ norm2.to(torch.int64))
    u_acc = (Wu.to(torch.int64) @ norm2.to(torch.int64))
    g_int = chained(g_acc, 0, "gate")
    u_int = chained(u_acc, 0, "up")
    silu_g = act_fn(g_int, abits)
    elt = ((silu_g * u_int) >> 4).clamp(-qmax_a, qmax_a)
    d_acc = (Wd.to(torch.int64) @ elt.to(torch.int64))
    d_int = chained(d_acc, 0, "down")
    hidden = (hidden + d_int).clamp(-qmax_a, qmax_a)

    final = _rms_norm_int_reference(hidden, gn, gamma_bits=16,
                                     eps=EPS, abits=abits)
    return final.to(torch.int32)


def rope_apply(
    packed: torch.Tensor,
    *,
    n_heads: int,
    head_dim: int,
    position: int,
    theta_base: float = 10000.0,
) -> torch.Tensor:
    """Apply RoPE to a packed [n_heads * head_dim] vector.

    RoPE rotates pairs of dimensions ``(2i, 2i+1)`` of each head by an
    angle ``position * theta_base ** (-2i / head_dim)``. Returns a new
    fp32 tensor of the same length; the input is not mutated.

    Position 0 is the identity rotation (cos=1, sin=0); position k > 0
    rotates each dimension pair by an increasing angle. Standard LLaMA
    convention.
    """
    if packed.numel() != n_heads * head_dim:
        raise ValueError(
            f"rope_apply: packed length {packed.numel()} != "
            f"n_heads * head_dim = {n_heads * head_dim}"
        )
    out = packed.clone().to(torch.float32)
    for h in range(n_heads):
        base = h * head_dim
        for i in range(head_dim // 2):
            inv_freq = theta_base ** (-2.0 * i / head_dim)
            ang = position * inv_freq
            ca, sa = math.cos(ang), math.sin(ang)
            x0 = float(out[base + 2 * i])
            x1 = float(out[base + 2 * i + 1])
            out[base + 2 * i] = x0 * ca - x1 * sa
            out[base + 2 * i + 1] = x0 * sa + x1 * ca
    return out


def llama_fp32_reference_logits_one_layer(
    *,
    config: dict,
    state_dict: dict[str, torch.Tensor],
    token_id: int,
    position: int = 0,
) -> torch.Tensor:
    """Pure-fp32 reference forward pass for the same 1-layer cut the
    int reference covers, useful as the gold against which the int
    reference (and the Verilog) are compared.

    No quantisation: every matmul is fp32, RMSNorm uses fp32 sqrt, SiLU
    uses real ``torch.nn.functional.silu``. The KV cache is empty (first
    token); RoPE is applied at ``position``.

    Returns the post-final-norm hidden vector as a 1-D fp32 tensor of
    length ``hidden_size``. Apply ``state_dict['model.embed_tokens.weight']``
    (or the lm_head weight when not tied) and argmax to get the predicted
    next token.
    """
    import torch.nn.functional as F
    HID = int(config["hidden_size"])
    H = int(config["num_attention_heads"])
    KV = int(config.get("num_key_value_heads", H))
    INTER = int(config["intermediate_size"])
    EPS = float(config.get("rms_norm_eps", 1e-5))
    HIDDEN_ACT = config.get("hidden_act", "silu")
    D = HID // H

    embed_w = state_dict["model.embed_tokens.weight"].to(torch.float32)
    hidden = embed_w[int(token_id)].clone()

    Wq = state_dict["model.layers.0.self_attn.q_proj.weight"].to(torch.float32)
    Wk = state_dict["model.layers.0.self_attn.k_proj.weight"].to(torch.float32)
    Wv = state_dict["model.layers.0.self_attn.v_proj.weight"].to(torch.float32)
    Wo = state_dict["model.layers.0.self_attn.o_proj.weight"].to(torch.float32)
    Wg = state_dict["model.layers.0.mlp.gate_proj.weight"].to(torch.float32)
    Wu = state_dict["model.layers.0.mlp.up_proj.weight"].to(torch.float32)
    Wd = state_dict["model.layers.0.mlp.down_proj.weight"].to(torch.float32)
    g1 = state_dict["model.layers.0.input_layernorm.weight"].to(torch.float32)
    g2 = state_dict["model.layers.0.post_attention_layernorm.weight"].to(torch.float32)
    gn = state_dict["model.norm.weight"].to(torch.float32)

    def rms(x: torch.Tensor, gamma: torch.Tensor) -> torch.Tensor:
        rms_val = torch.sqrt((x * x).mean() + EPS)
        return (x / rms_val) * gamma

    ROPE_THETA = float(config.get("rope_theta", 10000.0))
    norm1 = rms(hidden, g1)
    q = Wq @ norm1
    k = Wk @ norm1
    v = Wv @ norm1
    q = rope_apply(q, n_heads=H, head_dim=D, position=position,
                   theta_base=ROPE_THETA)
    k = rope_apply(k, n_heads=KV, head_dim=D, position=position,
                   theta_base=ROPE_THETA)
    # First-token attention against single K/V repeats V across head groups.
    attn_out = (
        v.view(KV, D)
        .repeat_interleave(H // KV, dim=0)
        .flatten()
    )
    o = Wo @ attn_out
    hidden = hidden + o

    norm2 = rms(hidden, g2)
    if HIDDEN_ACT in ("silu", "swiglu"):
        gate_act = F.silu(Wg @ norm2)
    elif HIDDEN_ACT == "gelu":
        gate_act = F.gelu(Wg @ norm2)
    else:
        raise ValueError(f"unknown hidden_act={HIDDEN_ACT!r}")
    up = Wu @ norm2
    elt = gate_act * up
    down = Wd @ elt
    hidden = hidden + down

    return rms(hidden, gn)


def compare_argmax_agreement(
    int_seq: list[int], fp32_seq: list[int],
) -> dict:
    """Compare two argmax token sequences and return a small report.

    Returns ``{"matches": int, "total": int, "agreement_pct": float,
    "first_disagreement_at": int | None}``.
    """
    if len(int_seq) != len(fp32_seq):
        raise ValueError(
            f"sequence lengths differ: {len(int_seq)} != {len(fp32_seq)}"
        )
    matches = 0
    first_diff = None
    for i, (a, b) in enumerate(zip(int_seq, fp32_seq)):
        if a == b:
            matches += 1
        elif first_diff is None:
            first_diff = i
    return {
        "matches": matches,
        "total": len(int_seq),
        "agreement_pct": 100.0 * matches / max(1, len(int_seq)),
        "first_disagreement_at": first_diff,
    }


def llama_int_reference_decode_loop(
    *,
    config: dict,
    state_dict: dict[str, torch.Tensor],
    initial_tokens: list[int],
    n_new_tokens: int,
    abits: int = 8,
    weight_bits: int = 8,
    requantize_params: list[dict[str, dict[str, list[int]]]] | None = None,
) -> list[int]:
    """Autoregressive decode loop: feed ``initial_tokens`` then sample
    ``n_new_tokens`` more by repeatedly calling the 1-layer forward pass.

    For each generated token: take the previous token's final_norm hidden
    state, project through lm_head (using the embed_tokens weight matrix
    when ``tie_word_embeddings`` is set, else lm_head.weight), argmax,
    feed the chosen token id back as the next position's input.

    The Verilog driver pattern that mirrors this loop:

      for k, tok in enumerate(initial_tokens + generated):
          drive token_id = tok, position = k, start = 1 for one cycle
          wait for done
          read next_token_id (the streaming-argmax output)
          generated.append(next_token_id)

    The Verilog attention block keeps its KV cache live across calls; the
    Python reference here doesn't (it's a first-token-only int chain),
    so multi-token quality is approximate. Use the iterative refinement
    + the Verilog pipeline for production-quality decode.

    Returns the list of generated token ids (length ``n_new_tokens``).
    """
    VOCAB = int(config["vocab_size"])
    TIE = bool(config.get("tie_word_embeddings", False))
    if TIE:
        lm_W = state_dict["model.embed_tokens.weight"].to(torch.float32)
    else:
        lm_W = state_dict.get("lm_head.weight")
        if lm_W is None:
            raise KeyError(
                "tie_word_embeddings=False but lm_head.weight is missing"
            )
        lm_W = lm_W.to(torch.float32)

    qmax_a = (1 << (abits - 1)) - 1

    generated: list[int] = []
    sequence = list(initial_tokens)
    for step in range(n_new_tokens):
        if not sequence:
            raise ValueError("initial_tokens must not be empty")
        last_tok = sequence[-1]
        position = len(sequence) - 1
        hidden_int8 = llama_int_reference_one_layer(
            config=config, state_dict=state_dict,
            token_id=last_tok, position=position,
            abits=abits, weight_bits=weight_bits,
            requantize_params=requantize_params,
        )
        # CPU-side lm_head + argmax. The 1-layer reference's hidden is
        # int8-bounded; map back to fp via /qmax_a so lm_W's float scale
        # absorbs it correctly.
        h_f = hidden_int8.to(torch.float32) / qmax_a
        logits = lm_W @ h_f   # [VOCAB]
        next_tok = int(logits.argmax().item())
        generated.append(next_tok)
        sequence.append(next_tok)
    return generated
