"""Vendor synth + place + route script generation.

The OSS CAD Suite path (yosys + nextpnr-ice40 / nextpnr-ecp5) is wired
into ``synth.py`` directly; this module emits the script templates for
the licensed tools that aren't installable on this host:

  Vivado     (Xilinx 7-series, Versal AI Edge, Alveo, ZynqMP)
  Quartus    (Intel Stratix, Cyclone, Agilex)
  Synopsys   (DC, Fusion Compiler)

Each template is a ready-to-run shell-or-Tcl script that, given the
emitted ``.v`` / ``.sv`` plus any sidecar weight ROMs, runs the standard
synth + opt + place + route flow and reports utilization / Fmax. Drop
the script into the working directory of the licensed-tools install and
invoke it through that vendor's CLI.

Public API:

  emit_vivado_tcl(verilog_path, top, part, *, period_ns=10.0, sdc_path=None)
      Returns Tcl source for ``vivado -mode batch -source <script>`` that
      runs synth_design + opt_design + place_design + route_design and
      writes a utilization + timing report.

  emit_quartus_qsf(verilog_path, top, part, *, period_ns=10.0)
      Returns the Quartus QSF + TCL pair as a ``{".qsf": str, ".tcl": str}``
      dict. The user runs ``quartus_sh --flow compile <project>``.

  emit_synopsys_dc_tcl(verilog_path, top, library, *, period_ns=10.0)
      Returns Synopsys Design Compiler Tcl that runs ``compile_ultra`` and
      reports area + timing against the named technology library.
"""
from __future__ import annotations

from pathlib import Path
from textwrap import dedent


def emit_vivado_tcl(
    verilog_path: str | Path,
    top: str,
    part: str,
    *,
    period_ns: float = 10.0,
    sdc_path: str | Path | None = None,
    extra_files: list[str | Path] | None = None,
) -> str:
    """Vivado batch-mode Tcl: synth_design + place_design + route_design,
    writing utilization + timing reports.

    Run with ``vivado -mode batch -source <script>``. Outputs land next
    to the script: ``<top>_utilization.rpt``, ``<top>_timing.rpt``,
    ``<top>_routed.dcp``.
    """
    extra = "\n".join(
        f"read_verilog -sv {Path(f).as_posix()}"
        for f in (extra_files or [])
    )
    sdc_line = (
        f"read_xdc {Path(sdc_path).as_posix()}"
        if sdc_path else
        f"create_clock -name clk -period {period_ns} [get_ports clk]"
    )
    return dedent(f"""\
        # Generated by safetensors2verilog.synth_vendor.emit_vivado_tcl.
        # Vivado batch-mode synth + opt + place + route script.
        #
        # Run: vivado -mode batch -source <this_file>
        #
        # Outputs (next to this script):
        #   {top}_utilization.rpt
        #   {top}_timing.rpt
        #   {top}_routed.dcp

        set part {part}
        set top {top}
        set period {period_ns}
        set verilog_path {Path(verilog_path).as_posix()}

        create_project -in_memory -part $part
        read_verilog -sv $verilog_path
        {extra}
        {sdc_line}

        synth_design -top $top -part $part
        opt_design
        place_design
        phys_opt_design -directive ExploreWithRemap
        route_design

        report_utilization -file ${{top}}_utilization.rpt
        report_timing -nworst 8 -file ${{top}}_timing.rpt
        report_clock_utilization -file ${{top}}_clock_util.rpt

        write_checkpoint -force ${{top}}_routed.dcp
        write_verilog -force -mode timesim ${{top}}_post_route.v
        write_sdf -force ${{top}}_post_route.sdf

        puts "DONE Vivado P&R for $top on $part"
        exit
        """)


def emit_quartus_qsf(
    verilog_path: str | Path,
    top: str,
    part: str,
    *,
    period_ns: float = 10.0,
    extra_files: list[str | Path] | None = None,
) -> dict[str, str]:
    """Quartus QSF (project settings) plus TCL flow script.

    Returns ``{".qsf": qsf_text, ".tcl": tcl_text}``. Save them as
    ``<top>.qsf`` and ``<top>_flow.tcl`` in the same directory, then::

        quartus_sh -t <top>_flow.tcl

    runs analyze + synthesize + fit + assemble + sta and emits
    ``<top>.fit.rpt`` + ``<top>.sta.rpt``.
    """
    extra_lines = "\n".join(
        f'set_global_assignment -name SYSTEMVERILOG_FILE {Path(f).as_posix()}'
        for f in (extra_files or [])
    )
    qsf = dedent(f"""\
        # Generated by safetensors2verilog.synth_vendor.emit_quartus_qsf.
        set_global_assignment -name FAMILY "Stratix 10"
        set_global_assignment -name DEVICE {part}
        set_global_assignment -name TOP_LEVEL_ENTITY {top}
        set_global_assignment -name SYSTEMVERILOG_FILE {Path(verilog_path).as_posix()}
        {extra_lines}
        set_global_assignment -name SDC_FILE {top}.sdc
        set_global_assignment -name PROJECT_OUTPUT_DIRECTORY output_files

        # Default per-instance: standard fitter + timing-driven router.
        set_global_assignment -name OPTIMIZATION_MODE "AGGRESSIVE PERFORMANCE"
        """)
    sdc = dedent(f"""\
        # Quartus SDC for {top}.
        create_clock -name clk -period {period_ns:.3f} [get_ports clk]
        derive_pll_clocks
        derive_clock_uncertainty
        """)
    tcl = dedent(f"""\
        # Generated by safetensors2verilog.synth_vendor.emit_quartus_qsf.
        # Quartus full-flow script for {top}.
        #
        # Run: quartus_sh -t {top}_flow.tcl

        load_package flow
        project_open {top}
        execute_flow -compile
        project_close

        puts "DONE Quartus full flow for {top}"
        """)
    return {".qsf": qsf, ".sdc": sdc, ".tcl": tcl}


def validate_tcl_script(text: str) -> list[str]:
    """Static checks on a Tcl-style synth script.

    Returns a list of issue messages. An empty list means the script
    passes the static checks. The checks are:
      * Balanced ``{`` / ``}`` braces.
      * Balanced ``[`` / ``]`` (for ``[get_ports ...]`` etc.).
      * Balanced ``"`` quotes per line.
      * No ``$`` followed by an undefined variable, where defined
        variables come from ``set <name> ...`` lines plus a small
        whitelist of vendor builtins.

    These catch the most common errors that would otherwise crash the
    licensed tools at runtime. They are not a substitute for actually
    running the tool, but they keep the emitted scripts well-formed.
    """
    import re as _re
    issues: list[str] = []
    open_brace = text.count("{")
    close_brace = text.count("}")
    if open_brace != close_brace:
        issues.append(
            f"unbalanced braces: open={open_brace}, close={close_brace}"
        )
    open_brack = text.count("[")
    close_brack = text.count("]")
    if open_brack != close_brack:
        issues.append(
            f"unbalanced brackets: open={open_brack}, close={close_brack}"
        )
    for ln, line in enumerate(text.splitlines(), 1):
        comment_idx = line.find("#")
        line_eff = line[:comment_idx] if comment_idx >= 0 else line
        if line_eff.count('"') % 2 != 0:
            issues.append(f"line {ln}: unbalanced double-quotes")
    defined = set(_re.findall(r"\bset\s+([A-Za-z_]\w*)", text))
    builtins = {
        "argv", "argc", "env", "tcl_platform", "auto_path",
        "errorInfo", "errorCode", "tcl_version",
    }
    for ln, line in enumerate(text.splitlines(), 1):
        comment_idx = line.find("#")
        eff = line[:comment_idx] if comment_idx >= 0 else line
        for use in _re.findall(r"\$\{?([A-Za-z_]\w*)", eff):
            if use not in defined and use not in builtins:
                issues.append(f"line {ln}: undefined variable ${use}")
    return issues


def emit_synopsys_dc_tcl(
    verilog_path: str | Path,
    top: str,
    library: str,
    *,
    period_ns: float = 10.0,
    extra_files: list[str | Path] | None = None,
) -> str:
    """Synopsys Design Compiler Tcl: read_verilog + compile_ultra + report.

    library: technology library .db path or vendor std-cell library name
             (e.g. ``"slow_typical_corner.db"`` or ``"saed_32nm_typ.db"``).
    """
    extra = "\n".join(
        f"read_verilog -sv {Path(f).as_posix()}"
        for f in (extra_files or [])
    )
    return dedent(f"""\
        # Generated by safetensors2verilog.synth_vendor.emit_synopsys_dc_tcl.
        # Synopsys Design Compiler script for {top}.
        #
        # Run: dc_shell -f <this_file>

        set top {top}
        set library {library}
        set verilog_path {Path(verilog_path).as_posix()}
        set period {period_ns}

        set target_library $library
        set link_library "* $library"

        read_verilog -sv $verilog_path
        {extra}

        current_design $top
        link
        check_design

        create_clock -name clk -period $period [get_ports clk]
        set_input_delay  -clock clk [expr $period * 0.4] [all_inputs]
        set_output_delay -clock clk [expr $period * 0.4] [all_outputs]
        set_max_area 0

        compile_ultra -no_autoungroup
        write_sdf -version 3.0 ${{top}}_post_synth.sdf
        write -format verilog -hierarchy -output ${{top}}_post_synth.v

        report_area > ${{top}}_area.rpt
        report_timing -delay max -max_paths 8 > ${{top}}_timing.rpt
        report_power > ${{top}}_power.rpt

        puts "DONE Synopsys DC compile for $top"
        exit
        """)
