"""Backend: lower a `GateGraph` to a synthesizable Verilog module.

Every gate compiles to one `wire` and one `assign`. With the threshold
form `output = 1 iff (Σ pos − Σ neg + bias) ≥ 0`, this is equivalent
to `(Σ pos + max(bias, 0)) ≥ (Σ neg + max(−bias, 0))`. We emit the
inequality in that form so all arithmetic stays unsigned and synthesis
maps cleanly to LUT + carry chain. Empty sums become the constant 0.
"""

from __future__ import annotations

import re
from typing import List

from .core import Gate, GateGraph


_VALID_IDENT = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")


def _sanitize(name: str) -> str:
    """Map a free-form signal name to a Verilog-legal identifier.

    Replaces dots, brackets, and `$`/`#` with underscores. Leading
    digits get prefixed with `_`. Empty strings become `_anon`.
    """
    if not name:
        return "_anon"
    out = re.sub(r"[^A-Za-z0-9_]", "_", name)
    if out[0].isdigit():
        out = "_" + out
    return out


def _const_or_signal(name: str) -> str:
    """Resolve `#0` and `#1` constant signals to Verilog literals; otherwise sanitise."""
    if name == "#0":
        return "1'b0"
    if name == "#1":
        return "1'b1"
    return _sanitize(name)


def _format_sum(terms: List[str]) -> str:
    """Emit a Verilog sum expression. Empty list -> '0'."""
    if not terms:
        return "0"
    if len(terms) == 1:
        return terms[0]
    return "(" + " + ".join(terms) + ")"


def _emit_gate_assign(gate: Gate) -> str:
    """Emit a single `assign` line for one gate."""
    pos_terms = [_const_or_signal(s) for s in gate.pos]
    neg_terms = [_const_or_signal(s) for s in gate.neg]

    # Move bias to whichever side keeps both sides non-negative.
    # gate fires iff (pos - neg + bias) >= 0
    #             iff (pos + max(bias, 0)) >= (neg + max(-bias, 0))
    if gate.bias > 0:
        pos_terms.append(str(gate.bias))
    elif gate.bias < 0:
        neg_terms.append(str(-gate.bias))

    lhs = _format_sum(pos_terms)
    rhs = _format_sum(neg_terms)
    return f"  assign {_sanitize(gate.name)} = ({lhs} >= {rhs});"


def emit_module(graph: GateGraph) -> str:
    """Emit the full Verilog text for `graph`.

    Inputs and outputs are 1-bit ports. Each gate is one wire + one
    assign. Gates must be topologically sorted in `graph.gates` so
    that every reference points to an already-declared signal.
    """
    # Validate topological order: every gate's inputs must be in the set of
    # already-declared signals (inputs + earlier gates) or be a constant.
    declared = set(graph.inputs) | {"#0", "#1"}
    for gate in graph.gates:
        for src in (*gate.pos, *gate.neg):
            if src not in declared:
                raise ValueError(
                    f"gate '{gate.name}' references undeclared signal '{src}'. "
                    f"GateGraph.gates must be topologically sorted."
                )
        declared.add(gate.name)

    for out in graph.outputs:
        if out not in declared:
            raise ValueError(f"output '{out}' is never produced by any gate")

    lines: List[str] = []
    lines.append("// Generated by safetensors2verilog.")
    lines.append("// Threshold-gate evaluation: each gate fires iff")
    lines.append("// (Σ positive-weighted inputs) − (Σ negative-weighted inputs) + bias ≥ 0.")
    lines.append("// All arithmetic is unsigned by construction.")
    lines.append("")

    port_decls: List[str] = []
    for name in graph.inputs:
        port_decls.append(f"  input wire {_sanitize(name)}")
    for name in graph.outputs:
        port_decls.append(f"  output wire {_sanitize(name)}")
    ports = ",\n".join(port_decls)
    lines.append(f"module {graph.top} (")
    lines.append(ports)
    lines.append(");")
    lines.append("")

    # Internal wires (everything that's a gate but not an output)
    output_set = set(graph.outputs)
    internal = [g.name for g in graph.gates if g.name not in output_set]
    if internal:
        lines.append("  // internal nets")
        for name in internal:
            lines.append(f"  wire {_sanitize(name)};")
        lines.append("")

    lines.append("  // gate evaluations")
    for gate in graph.gates:
        lines.append(_emit_gate_assign(gate))
    lines.append("")
    lines.append(f"endmodule // {graph.top}")
    lines.append("")

    return "\n".join(lines)
